Repository openhab/openhab-core, pull requests merged in 2019-08, with the labels that each got.

#972 Unique job key for createTimer in DSL rule
  bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/actions/ScriptExecution.java
Labels: DSL

#964 [automation] Update configDescriptions for jsr223.ScriptedTrigger (#962)
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/resources/ESH-INF/automation/moduletypes/PrivateScriptedTypes.json
Labels: automation, bug

#969 Added feature for FasterXML Jackson bundles
  features/karaf/openhab-tp/src/main/feature/feature.xml
Labels: infrastructure

#990 Fix Incorrect unit symbol for Byte and add unit symbol for Octet.
  bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/unit/SmartHomeUnits.java
Labels: UoM

#989 [semantics] Specified service for component description
  bundles/org.openhab.core.semantics/src/main/java/org/eclipse/smarthome/core/semantics/internal/SemanticsMetadataProvider.java
  bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/items/ItemRegistryChangeListener.java
Labels: bug

#982 [rest] Streamline DTO serialization for REST item resources
  bundles/org.openhab.core.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/item/ItemResource.java
  bundles/org.openhab.core.io.rest/src/main/java/org/eclipse/smarthome/io/rest/JSONResponse.java
  bundles/org.openhab.core.io.rest/src/main/java/org/eclipse/smarthome/io/rest/Stream2JSONInputStream.java
  itests/org.openhab.core.io.rest.core.tests/src/main/java/org/eclipse/smarthome/io/rest/core/internal/item/ItemResourceOSGiTest.java
Labels: REST/SSE

#1003 [rulehli] Added "configurationPid"
  bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/internal/RuleHumanLanguageInterpreter.java
Labels: bug

#996 Fix gamma correction in HSBType for color conversion from sRGB to CIE XYZ and back
  bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/types/HSBType.java
Labels: bug

#1007 [infrastructure] bump SAT to 0.7.0
  bundles/org.openhab.core.io.http.auth/src/main/java/org/eclipse/smarthome/io/http/auth/internal/AuthenticationHandler.java
  bundles/org.openhab.core.io.net/src/main/java/org/eclipse/smarthome/io/net/http/internal/ExtensibleTrustManagerImpl.java
  bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/service/ReadyServiceImpl.java
  pom.xml
  tools/static-code-analysis/checkstyle/ruleset.properties
Labels: infrastructure

#1013 Removed duplicate dependencies
  bom/runtime/pom.xml
Labels: infrastructure
