Repository openhab/openhab-core, pull requests merged in 2019-11, with the labels that each got.

#1173 Added 'InstanceCreator' for 'PersistedItem'
  bundles/org.openhab.core.storage.mapdb/src/main/java/org/eclipse/smarthome/storage/mapdb/internal/MapDbStorage.java
  bundles/org.openhab.core.storage.mapdb/src/test/java/org/eclipse/smarthome/storage/mapdb/internal/MapDbStorageServiceTest.java
  bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/items/ManagedItemProvider.java
  itests/org.openhab.core.tests/src/main/java/org/eclipse/smarthome/core/items/ManagedItemProviderOSGiTest.java
Labels: bug

#1067 Consider more than one value when applying the default value(s) for Things and Channels
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/util/ConfigurationNormalizer.java
  bundles/org.openhab.core.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigUtil.java
  bundles/org.openhab.core.config.core/src/main/java/org/eclipse/smarthome/config/core/internal/normalization/ListNormalizer.java
  bundles/org.openhab.core.config.core/src/main/java/org/eclipse/smarthome/config/core/internal/normalization/NormalizerFactory.java
  bundles/org.openhab.core.config.core/src/test/java/org/eclipse/smarthome/config/core/ConfigUtilTest.java
  bundles/org.openhab.core.model.thing/src/org/eclipse/smarthome/model/thing/internal/GenericThingProvider.xtend
  bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingFactoryHelper.java
  bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerImpl.java
  itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/binding/ThingFactoryTest.java
Labels: enhancement

#1101 Add source code formatting as part of build process using spotless maven plugin
  pom.xml
Labels: infrastructure

#1169 Evolutions of the Ephemeris module
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/EphemerisConditionHandler.java
  bundles/org.openhab.core.ephemeris/src/main/java/org/eclipse/smarthome/core/ephemeris/EphemerisManager.java
  bundles/org.openhab.core.ephemeris/src/main/java/org/eclipse/smarthome/core/ephemeris/internal/EphemerisManagerImpl.java
  bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/actions/Ephemeris.java
  itests/org.openhab.core.ephemeris.tests/src/main/java/org/eclipse/smarthome/core/ephemeris/internal/EphemerisManagerImplOSGiTest.java
  itests/org.openhab.core.ephemeris.tests/src/main/resources/events.xml
Labels: enhancement

#1191 Fix unstable MqttBrokerConnectionTests
  bundles/org.openhab.core.io.transport.mqtt/pom.xml
  bundles/org.openhab.core.io.transport.mqtt/src/test/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnectionTests.java
Labels: test

#1193 [itest] Exclude json and mapdb storage by default for itests
  itests/itest-common.bndrun
  itests/itest-include.bndrun
  itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun
  itests/org.openhab.core.automation.integration.tests/itest.bndrun
  itests/org.openhab.core.automation.module.core.tests/itest.bndrun
  itests/org.openhab.core.automation.module.script.defaultscope.tests/itest.bndrun
  itests/org.openhab.core.automation.module.script.tests/itest.bndrun
  itests/org.openhab.core.automation.module.timer.tests/itest.bndrun
  itests/org.openhab.core.automation.tests/itest.bndrun
  itests/org.openhab.core.binding.xml.tests/itest.bndrun
  itests/org.openhab.core.config.core.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun
  itests/org.openhab.core.config.dispatch.tests/itest.bndrun
  itests/org.openhab.core.config.xml.tests/itest.bndrun
  itests/org.openhab.core.ephemeris.tests/itest.bndrun
  itests/org.openhab.core.io.rest.core.tests/itest.bndrun
  itests/org.openhab.core.model.core.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.persistence.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
  itests/org.openhab.core.storage.json.tests/itest.bndrun
  itests/org.openhab.core.tests/itest.bndrun
  itests/org.openhab.core.thing.tests/itest.bndrun
  itests/org.openhab.core.thing.xml.tests/itest.bndrun
Labels: infrastructure, test

#1203 [MQTT] PeriodicReconnectStrategy: fix fields init
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/reconnect/PeriodicReconnectStrategy.java
Labels: bug

#1201 Bump Californium to 2.0.0-RC1
  features/karaf/openhab-tp/src/main/feature/feature.xml
Labels: API breaking

#1224 [rest] Use correct wildcard for mandatory path parameters
  bundles/org.openhab.core.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/extensions/ExtensionResource.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/item/ItemResource.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/persistence/PersistenceResource.java
  bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResource.java
  bundles/org.openhab.core.io.rest.voice/src/main/java/org/eclipse/smarthome/io/rest/voice/internal/VoiceResource.java
Labels: REST/SSE

#1230 [thing] Call `removeItem()` with item name instead of `ThingUID`
  bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ChannelItemProvider.java
  bundles/org.openhab.core.thing/src/test/java/org/eclipse/smarthome/core/thing/internal/ChannelItemProviderTest.java
Labels: bug

#1228 Create tags_no.properties
  bundles/org.openhab.core.semantics/src/main/resources/tags_no.properties
Labels: i18n/l10n

#1240 Correcting Issue #1231
  bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeType.java
  bundles/org.openhab.core/src/test/java/org/eclipse/smarthome/core/library/types/DecimalTypeTest.java
Labels: bug

#1243 Set 'UNINITIALIZED' -> 'HANDLER_MISSING_ERROR' after enabling a thing and handler / factory is missing
  bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerImpl.java
  itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiJavaTest.java
Labels: bug

#1248 Fix check which allows QoS 3
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnection.java
Labels: bug
