Repository openhab/openhab-core, pull requests merged in 2019-04, with the labels that each got.

#688 Require successful Travis CI Java 11 build
  .travis.yml
  pom.xml
Labels: infrastructure

#697 Enable Semantics Integration Tests
  itests/org.openhab.core.semantics.tests/itest.bndrun
  itests/pom.xml
Labels: infrastructure, rebuild

#700 Enable Network I/O HTTP Integration Tests
  itests/org.openhab.core.io.http.tests/itest.bndrun
  itests/org.openhab.core.io.http.tests/src/main/java/org/eclipse/smarthome/io/http/internal/HttpContextFactoryServiceImplTest.java
  itests/pom.xml
Labels: infrastructure

#693 [core] Improved thing / bridge performance
  bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/Bridge.java
  bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/Thing.java
  bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/builder/BridgeBuilder.java
  bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/builder/ThingBuilder.java
  bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/BridgeImpl.java
  bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingImpl.java
  bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/util/ThingHelper.java
  bundles/org.openhab.core.thing/src/test/java/org/eclipse/smarthome/core/thing/internal/ThingImplTest.java
  itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/binding/ThingFactoryTest.java
  itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/events/ThingEventFactoryTest.java
Labels: enhancement

#723 Update Karaf to 4.2.4 in openHAB add-ons Parent POM
  features/p2/poms/pom.xml
Labels: karaf

#741 Attach source JARs without forking to fix Jenkins warnings
  bundles/pom.xml
Labels: infrastructure

#724 [JSR223] Sort by filename instead of path
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileWatcher.java
Labels: automation

#745 Import 'SmartHomeUnits' in Script Scope
  bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/scoping/ScriptImplicitlyImportedTypes.java
Labels: bug

#756 Enable Magic Bundle Tests
  itests/org.openhab.core.magic.tests/.classpath
  itests/org.openhab.core.magic.tests/itest.bndrun
  itests/org.openhab.core.magic.tests/src/main/java/org/eclipse/smarthome/magic/binding/internal/MagicHandlerFactoryTest.java
  itests/org.openhab.core.magic.tests/src/main/java/org/eclipse/smarthome/magic/binding/internal/MagicServiceImplTest.java
  itests/pom.xml
Labels: test

#655 Added i18n feature for dynamic state descriptions
  bundles/org.openhab.core.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/EnrichedItemDTOMapper.java
  bundles/org.openhab.core.test.magic/src/main/java/org/eclipse/smarthome/magic/binding/MagicBindingConstants.java
  bundles/org.openhab.core.test.magic/src/main/java/org/eclipse/smarthome/magic/binding/handler/MagicDynamicStateDescriptionThingHandler.java
  bundles/org.openhab.core.test.magic/src/main/java/org/eclipse/smarthome/magic/binding/internal/MagicDiscoveryService.java
  bundles/org.openhab.core.test.magic/src/main/java/org/eclipse/smarthome/magic/binding/internal/MagicDynamicStateDescriptionProvider.java
  bundles/org.openhab.core.test.magic/src/main/java/org/eclipse/smarthome/magic/binding/internal/MagicHandlerFactory.java
  bundles/org.openhab.core.test.magic/src/main/resources/ESH-INF/i18n/magic_de.properties
  bundles/org.openhab.core.test.magic/src/main/resources/ESH-INF/thing/channel-types.xml
  bundles/org.openhab.core.test.magic/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseDynamicStateDescriptionProvider.java
  bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java
  bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/i18n/ChannelTypeI18nLocalizationService.java
  bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ChannelStateDescriptionProvider.java
  bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/DynamicStateDescriptionProvider.java
  bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/items/ItemStateConverterImpl.java
  bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/types/CommandDescriptionImpl.java
  bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/types/StateDescriptionFragmentImpl.java
  bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/items/GenericItem.java
  bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/items/NumberItem.java
  bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/types/CommandDescription.java
  bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/types/CommandDescriptionBuilder.java
  bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/types/CommandOption.java
  bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/types/StateDescription.java
  bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/types/StateDescriptionFragment.java
  bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/types/StateDescriptionFragmentBuilder.java
  bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/types/StateDescriptionFragmentProvider.java
  bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/types/StateOption.java
  itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/internal/SimpleThingTypeProvider.java
  itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/type/ChannelStateDescriptionProviderOSGiTest.java
Labels: i18n/l10n

#589 Added maven archetype project to generate binding skeletons
  pom.xml
  tools/archetype/binding/.project
  tools/archetype/binding/pom.xml
  tools/archetype/binding/src/main/resources/META-INF/archetype-post-generate.groovy
  tools/archetype/binding/src/main/resources/META-INF/maven/archetype-metadata.xml
  tools/archetype/binding/src/main/resources/archetype-resources/.classpath
  tools/archetype/binding/src/main/resources/archetype-resources/.project
  tools/archetype/binding/src/main/resources/archetype-resources/NOTICE
  tools/archetype/binding/src/main/resources/archetype-resources/README.md
  tools/archetype/binding/src/main/resources/archetype-resources/pom.xml
  tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__BindingConstants.java
  tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__Configuration.java
  tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__Handler.java
  tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__HandlerFactory.java
  tools/archetype/binding/src/main/resources/archetype-resources/src/main/resources/ESH-INF/binding/binding.xml
  tools/archetype/binding/src/main/resources/archetype-resources/src/main/resources/ESH-INF/i18n/__bindingId___xx_XX.properties
  tools/archetype/binding/src/main/resources/archetype-resources/src/main/resources/ESH-INF/thing/thing-types.xml
  tools/archetype/pom.xml
  tools/pom.xml
Labels: infrastructure

#764 automation: remove specific handling for CompositeModuleHandlerFactory
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
Labels: automation

#771 Added i18n feature for dynamic command descriptions
  bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseDynamicCommandDescriptionProvider.java
  bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/i18n/ChannelTypeI18nLocalizationService.java
  bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/DynamicCommandDescriptionProvider.java
  bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/types/CommandDescriptionBuilder.java
  bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/types/CommandOption.java
Labels: i18n/l10n
