Repository openhab/openhab-core, pull requests merged in 2019-06, with the labels that each got.

#842 Use bnd for including resources to workaround infinite Eclipse builds
  pom.xml
Labels: bug, infrastructure

#851 automation: Refactoring of 'DefaultScriptScopeProvider'
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/DefaultScriptScopeProvider.java
Labels: automation

#854 [dsl] Added 'RefreshType.REFRESH' and 'BinaryPrefix' to imports
  bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/scoping/ScriptImplicitlyImportedTypes.java
  bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/scoping/StateAndCommandProvider.java
Labels: DSL rules
