Repository openhab/openhab-core, pull requests merged in 2020-11, with the labels that each got.

#1789 [charts] Added support for QuantityTypes to DefaultChartProvider
  bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/defaultchartprovider/DefaultChartProvider.java
Labels: enhancement

#1795 [automation] Added NPE checks for result of 'getSymbolicName()' methods
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/AbstractResourceBundleProvider.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/RuleResourceBundleImporter.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/Vendor.java
Labels: automation, bug

#1563 [persistence] Allow max, min and avg calculations on other types
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/PersistenceServiceRegistry.java
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
  bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java
  bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/TestPersistenceService.java
Labels: enhancement, persistence

#1806 [automation] Fixed NPE when no command is given in a member-of-group trigger
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GroupCommandTriggerHandler.java
Labels: bug

#1811 Do not provide unit information for plain number items
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/NumberItem.java
Labels: bug

#1809 [automation] Correctly map the state context variable of the ItemStateEvent to the implicit var newState
  bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java
Labels: automation, bug

#1817 Changed comparison from equals() to reference
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ChannelCommandDescriptionProvider.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ChannelStateDescriptionProvider.java
Labels: bug

#1756 [REST] Apply metadata selector regex on all namespaces
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/MetadataSelectorMatcher.java
  bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/internal/item/MetadataSelectorMatcherTest.java
Labels: REST/SSE

#1819 [automation] Create separate DSLScriptEngine instance for every handler
  bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngineFactory.java
Labels: automation, bug, critical

#1825 Harden item creation by checking for validity of name
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/ManagedItemProvider.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/dto/ItemDTOMapper.java
Labels: bug

#1803 Added expire functionality as core framework feature
  bundles/org.openhab.core.model.item/src/org/openhab/core/model/item/internal/GenericItemProvider.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/events/AbstractEvent.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ExpireManager.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/ExpireManagerTest.java
Labels: enhancement

#1838 [uom] Added support for MetricPrefix combined with byte and use byte as default instead of octet
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/SmartHomeUnits.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java
Labels: UoM, enhancement

#1807 [REST Auth] Remove user access to things
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java
Labels: enhancement

#1726 [profiles] Added 'Hysteresis' profile
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemHysteresisStateProfile.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemOffsetProfile.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemProfileFactory.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/profiles/SystemProfiles.java
  bundles/org.openhab.core.thing/src/main/resources/OH-INF/config/hyteresisProfile.xml
  bundles/org.openhab.core.thing/src/main/resources/OH-INF/i18n/SystemProfiles_de.properties
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/SystemHysteresisStateProfileTest.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/profiles/SystemProfileFactoryOSGiTest.java
Labels: enhancement

#1857 [automation] Make rule engine use a threadpool
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/TriggerHandlerCallbackImpl.java
Labels: automation, enhancement

#1856 Prevent NPE on shutdown by making maps in DSLRuleProvider thread safe
  bundles/org.openhab.core.model.rule.runtime/src/org/openhab/core/model/rule/runtime/internal/DSLRuleProvider.java
Labels: bug

#1858 Adapted event handler thread names to naming convention
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/events/EventHandler.java
Labels: enhancement

#1869 [automation] Request automation thread pool as a scheduled pool
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/TriggerHandlerCallbackImpl.java
Labels: automation, bug

#1870 [automation] Synchronize the executions of each rule
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
Labels: automation, bug
