Repository openhab/openhab-core, pull requests merged in 2020-02, with the labels that each got.

#1347 Units for reactive and apparent power
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/SmartHomeUnits.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/SmartHomeUnitsTest.java
Labels: enhancement

#1346 ChannelDTO bugfixes
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/dto/ChannelDTO.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/dto/ChannelDTOMapper.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/dto/StrippedThingTypeDTOMapper.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/dto/ThingDTOMapper.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/AutoUpdatePolicy.java
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/binding/builder/ThingBuilderTest.java
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/dto/ChannelDTOTest.java
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/dto/ThingDTOTest.java
Labels: bug

#1359 Removed dependency on 'org.apache.commons.exec'
  bom/compile/pom.xml
  bom/runtime/pom.xml
  bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/exec/ExecUtil.java
  bundles/org.openhab.core.io.net/src/test/java/org/openhab/core/io/net/exec/ExecUtilTest.java
  features/karaf/openhab-tp/src/main/feature/feature.xml
  itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun
  itests/org.openhab.core.model.core.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.persistence.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
Labels: API breaking, infrastructure

#1368 [units] Added Bq/m³ and ppb units
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/SmartHomeUnits.java
Labels: enhancement

#1367 [automation] Corrected issue where scripts were not starting when OH restarted
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileWatcher.java
Labels: automation, bug

#1375 Ephemeris: isBankHoliday(offset, filename) now really uses the filename
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Ephemeris.java
Labels: bug

#1376 [DSL] Added implicit import for units to rule models
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/scoping/ScriptImportSectionNamespaceScopeProvider.java
Labels: DSL rules, bug
