Repository openhab/openhab-core, pull requests merged in 2020-09, with the labels that each got.

#1551 [persistence] Added methods to calculate variance and standard deviation for persisted items
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
  bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java
  bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/TestPersistenceService.java
  itests/org.openhab.core.persistence.tests/.classpath
  itests/org.openhab.core.persistence.tests/.project
  itests/org.openhab.core.persistence.tests/NOTICE
  itests/org.openhab.core.persistence.tests/itest.bndrun
  itests/org.openhab.core.persistence.tests/pom.xml
  itests/pom.xml
Labels: enhancement, persistence

#1481 [discovery] Added validation for relation between ThingUID and BridgeUID
  bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/DiscoveryResultBuilder.java
  bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/DiscoveryResultBuilderTest.java
  itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/DiscoveryServiceMock.java
  itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/DiscoveryServiceMockOfBridge.java
  itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/DiscoveryServiceRegistryOSGiTest.java
  itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/internal/InboxOSGiTest.java
Labels: bug

#1623 Remove deprecated FilterCriteria methods
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/FilterCriteria.java
  bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/TestPersistenceService.java
Labels: API breaking

#1622 Remove deprecated NetUtil methods
  bundles/org.openhab.core/src/main/java/org/openhab/core/net/NetUtil.java
Labels: API breaking

#1629 Remove deprecated methods from Configuration, UID and ThingHelper
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/Configuration.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/UID.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/util/ThingHelper.java
Labels: API breaking

#1414 Removed deprecated constructors and methods from Thing API
  bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/DiscoveryResultBuilder.java
  bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/dto/DiscoveryResultDTO.java
  bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/DiscoveryResultImpl.java
  bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/internal/DiscoveryResultImplTest.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/profile/ProfileTypeResource.java
  bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/internal/channel/ChannelTypeResourceTest.java
  bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/GenericThingProvider.xtend
  bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/validation/ThingValidator.xtend
  bundles/org.openhab.core.thing.xml/src/main/java/org/openhab/core/thing/xml/internal/ChannelTypeConverter.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/Channel.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/ChannelUID.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/Thing.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/ThingUID.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/UID.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/i18n/ChannelGroupTypeI18nLocalizationService.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/i18n/ChannelTypeI18nLocalizationService.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/type/AbstractChannelTypeBuilder.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/type/StateChannelTypeBuilderImpl.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/type/TriggerChannelTypeBuilderImpl.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/AbstractDescriptionType.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/BridgeType.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/ChannelDefinition.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/ChannelGroupType.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/ChannelGroupTypeUID.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/ChannelType.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/ChannelTypeProvider.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/ChannelTypeUID.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/ThingType.java
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/ThingUIDTest.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/common/AbstractUID.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/ChangeThingTypeOSGiTest.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ChannelStateDescriptionProviderOSGiTest.java
Labels: API breaking, awaiting other PR

#1665 Remove deprecated BaseThingHandler.initialize()
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandler.java
  itests/org.openhab.core.model.thing.tests/src/main/java/org/openhab/core/model/thing/test/hue/GenericThingProviderTest4.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingManagerOSGiJavaTest.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingRegistryOSGiTest.java
Labels: API breaking

#1667 Remove deprecate default methods
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigOptionProvider.java
  bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/DiscoveryListener.java
Labels: API breaking

#1669 Remove deprecated handleUpdate from ThingHandler
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandler.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/ThingHandler.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/ProfileCallbackImpl.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemDefaultProfile.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemOffsetProfile.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/profiles/ProfileCallback.java
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/SystemDefaultProfileTest.java
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/SystemOffsetProfileTest.java
Labels: API breaking

#1666 Fix ConfigurableService deprecations
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigurableService.java
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigurableServiceUtil.java
  bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/ConfigurableServiceUtilTest.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/service/ConfigurableServiceResource.java
  bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/internal/MagicServiceImpl.java
  bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/internal/automation/modules/MagicMultiActionMarker.java
  bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/internal/automation/modules/MagicSingleActionService.java
  bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/service/MagicMultiInstanceServiceMarker.java
Labels: API breaking

#1668 Remove deprecated MQTT transport code
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnection.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/ssl/CustomTrustManagerFactory.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/sslcontext/AcceptAllCertificatesSSLContext.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/sslcontext/CustomSSLContextProvider.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/sslcontext/SSLContextProvider.java
Labels: API breaking

#1671 Remove remaining deprecated MQTT transport code
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnection.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnectionConfig.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/MqttException.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/MqttServiceImpl.java
  bundles/org.openhab.core.io.transport.mqtt/src/test/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnectionTests.java
Labels: API breaking
