Repository openhab/openhab-core, pull requests merged in 2020-10, with the labels that each got.

#1703 Added action for 'isBankHoliday(<file>)'
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Ephemeris.java
Labels: enhancement

#1705 Fix and cleanup logging in ExecUtil
  bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/exec/ExecUtil.java
Labels: enhancement

#1718 Fixed initialization of group items with aggregation functions
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/ManagedItemProvider.java
  itests/org.openhab.core.tests/src/main/java/org/openhab/core/items/ItemRegistryImplTest.java
Labels: bug

#1720 Fixed missing item resolution of DSL scripts created through the UI
  bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java
Labels: bug

#1721 upgraded JmDNS to version 3.5.6
  bom/compile/pom.xml
  bom/runtime/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
  itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
Labels: enhancement

#1725 Fix JSR223 JavaScript files not loading
  features/karaf/openhab-core/src/main/feature/feature.xml
Labels: automation

#1722 Add Automation extension type
  bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java
  bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonService.java
Labels: automation, karaf

#1704 [REST] Added validation for relation between ThingUID and BridgeUID
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingRegistryOSGiTest.java
Labels: REST/SSE, bug

#1730 [automation] Fixed IndexOutOfBoundsException in ScriptModuleTypeProvider
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/provider/ScriptModuleTypeProvider.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/type/ActionType.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/type/ConditionType.java
Labels: automation, bug

#1744 [automation] Sort audio sinks for say and playSound actions
  bundles/org.openhab.core.automation.module.media/src/main/java/org/openhab/core/automation/module/media/internal/MediaActionTypeProvider.java
Labels: automation

#1735 [REST Auth] API tokens & openhab:users console command
  bundles/org.openhab.core.io.console/src/main/java/org/openhab/core/io/console/internal/extension/UserConsoleCommandExtension.java
  bundles/org.openhab.core.io.http.auth/pages/authorize.html
  bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/AbstractAuthPageServlet.java
  bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/AuthorizePageServlet.java
  bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/ChangePasswordPageServlet.java
  bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/CreateAPITokenPageServlet.java
  bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/AuthFilter.java
  bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/AuthenticationSecurityContext.java
  bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/JwtHelper.java
  bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/JwtSecurityContext.java
  bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/TokenResource.java
  bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/UserApiTokenDTO.java
  bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/UserSecurityContext.java
  bundles/org.openhab.core.io.rest.auth/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.core/src/main/java/org/openhab/core/auth/Authentication.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/auth/ManagedUser.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/auth/UserApiToken.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/auth/UserApiTokenCredentials.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/auth/UserRegistry.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/auth/UserRegistryImpl.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/internal/auth/UserRegistryImplTest.java
Labels: REST/SSE, enhancement

#1723 [cache] Added 'ByteArrayFileCache'
  bundles/org.openhab.core/.classpath
  bundles/org.openhab.core/src/main/java/org/openhab/core/OpenHAB.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/cache/ByteArrayFileCache.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/cache/ByteArrayFileCacheTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/cache/ExpiringCacheMapTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/cache/ExpiringCacheTest.java
Labels: enhancement

#1754 [ui] Added unit test for read-only Number- and String-Items to not return a Selection Element
  bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java
  bundles/org.openhab.core.ui/src/test/java/org/openhab/core/ui/internal/items/ItemUIRegistryImplTest.java
Labels: UI, test

#1750 [automation] Allow dashes in rule file names
  bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java
Labels: bug

#1773 Fixed typo in class name TrustAllTrustMananger.
  bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/TrustAllTrustManager.java
Labels: API breaking, awaiting other PR
