Repository openhab/openhab-core, pull requests merged in 2020-12, with the labels that each got.

#1873 Fixed Hysteresis Profile config description
  bundles/org.openhab.core.thing/src/main/resources/OH-INF/config/hyteresisProfile.xml
  bundles/org.openhab.core.thing/src/main/resources/OH-INF/i18n/SystemProfiles_de.properties
Labels: bug

#1770 [automation] Provide triggering item name in the rule context
  bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/jvmmodel/RulesJvmModelInferrer.xtend
  bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/jvmmodel/ScriptJvmModelInferrer.xtend
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/GroupItemStateChangedEvent.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemCommandEvent.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemEvent.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemEventFactory.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemStateChangedEvent.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemStateEvent.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemStatePredictedEvent.java
Labels: API breaking, enhancement

#1854 [automation] Added Actions for Play and Say which sets the volume
  bundles/org.openhab.core.automation.module.media/src/main/java/org/openhab/core/automation/module/media/internal/MediaActionTypeProvider.java
  bundles/org.openhab.core.automation.module.media/src/main/java/org/openhab/core/automation/module/media/internal/MediaModuleHandlerFactory.java
  bundles/org.openhab.core.automation.module.media/src/main/java/org/openhab/core/automation/module/media/internal/PlayActionHandler.java
  bundles/org.openhab.core.automation.module.media/src/main/java/org/openhab/core/automation/module/media/internal/SayActionHandler.java
Labels: automation, enhancement

#1880 Cache safe call proxies for profiles instead of continuously recreating them
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/CommunicationManager.java
Labels: enhancement

#1890 [automation] Reverted the introduction of an automation threadpool
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/TriggerHandlerCallbackImpl.java
  bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/jvmmodel/RulesRefresher.java
Labels: enhancement

#1896 Rename classes with "SmartHome" in their name
  bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioServlet.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/DefaultScriptScopeProvider.java
  bundles/org.openhab.core.io.http/src/main/java/org/openhab/core/io/http/internal/OpenHABHttpContext.java
  bundles/org.openhab.core.io.http/src/main/java/org/openhab/core/io/http/servlet/BaseOpenHABServlet.java
  bundles/org.openhab.core.io.http/src/main/java/org/openhab/core/io/http/servlet/OpenHABBundleServlet.java
  bundles/org.openhab.core.io.http/src/main/java/org/openhab/core/io/http/servlet/OpenHABServlet.java
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/lib/NumberExtensions.java
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/scoping/ScriptImplicitlyImportedTypes.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemHysteresisStateProfile.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemOffsetProfile.java
  bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/internal/IconServlet.java
  bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/ChartServlet.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/library/unit/UnitInitializer.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/PercentType.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/Units.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/types/util/UnitUtils.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/dimension/VolumetricFlowRateTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/PercentTypeTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/UnitsTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/types/util/UnitUtilsTest.java
  itests/org.openhab.core.model.script.tests/src/main/java/org/openhab/core/model/script/engine/ScriptEngineOSGiTest.java
  itests/org.openhab.core.model.script.tests/src/main/java/org/openhab/core/model/script/lib/NumberExtensionsTest.java
Labels: API breaking

#1860 Remove semantic metadata on item tag removal
  bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/internal/SemanticsMetadataProvider.java
  bundles/org.openhab.core.semantics/src/test/java/org/openhab/core/semantics/internal/SemanticsMetadataProviderTest.java
Labels: bug

#1909 Improve ChannelLinkNotifier.removed and AbstractUID.getAsString performance
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ChannelLinkNotifier.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/common/AbstractUID.java
Labels: enhancement

#1914 Implemented start level service
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileWatcher.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleRegistryImpl.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/TriggerHandlerCallbackImpl.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/SystemTriggerHandler.java
  bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/EventLogger.java
  bundles/org.openhab.core.model.item/.classpath
  bundles/org.openhab.core.model.rule.runtime/src/org/openhab/core/model/rule/runtime/internal/DSLRuleProvider.java
  bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/jvmmodel/RulesRefresher.java
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceManagerImpl.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingRegistryImpl.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/ItemChannelLinkRegistry.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/common/registry/AbstractRegistry.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ItemRegistryImpl.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/MetadataRegistryImpl.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/service/StartLevelService.java
  itests/org.openhab.core.automation.integration.tests/itest.bndrun
  itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationJsonTest.java
  itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationTest.java
  itests/org.openhab.core.automation.module.core.tests/src/main/java/org/openhab/core/automation/internal/module/RunRuleModuleTest.java
  itests/org.openhab.core.automation.module.core.tests/src/main/java/org/openhab/core/automation/internal/module/RuntimeRuleTest.java
  itests/org.openhab.core.automation.module.script.tests/itest.bndrun
  itests/org.openhab.core.automation.module.script.tests/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/DemoScriptRule.json
  itests/org.openhab.core.automation.module.script.tests/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/ScriptRuleOSGiTest.java
  itests/org.openhab.core.automation.module.timer.tests/src/main/java/org/openhab/core/automation/module/timer/internal/BasicConditionHandlerTest.java
  itests/org.openhab.core.automation.module.timer.tests/src/main/java/org/openhab/core/automation/module/timer/internal/RuntimeRuleTest.java
  itests/org.openhab.core.automation.tests/src/main/java/org/openhab/core/automation/event/RuleEventTest.java
  itests/org.openhab.core.model.rule.tests/src/main/java/org/openhab/core/model/rule/runtime/DSLRuleProviderTest.java
Labels: automation, enhancement

#1917 Register CommunicationManager to listen on ItemChannelLink changes
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/CommunicationManager.java
Labels: bug

#1919 Improved startup logging and avoid scripts being loaded in start level service thread
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileWatcher.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/service/StartLevelService.java
Labels: enhancement

#1923 [automation] Added config options for start level trigger
  bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/SystemTriggers.json
Labels: automation, enhancement

#1922 [automation] Always set the value of implicit vars
  bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java
Labels: automation, bug

#1920 increase the rule refresher delay
  bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/jvmmodel/RulesRefresher.java
Labels: enhancement

#1918 Fix remaining deprecations
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigDescriptionParameterGroup.java
  bundles/org.openhab.core.thing.xml/src/main/java/org/openhab/core/thing/xml/internal/ChannelTypeConverter.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/Channel.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/builder/ChannelBuilder.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/i18n/ChannelTypeI18nLocalizationService.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/type/StateChannelTypeBuilderImpl.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/type/TriggerChannelTypeBuilderImpl.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/ChannelType.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/StateChannelTypeBuilder.java
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/type/ChannelTypeBuilderTest.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ChannelStateDescriptionProviderOSGiTest.java
Labels: API breaking

#1932 [REST] Add firmwareStatus to things in summary mode
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java
Labels: bug

#1933 Fixed Inbox approve API annotation
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/discovery/InboxResource.java
Labels: bug

#1939 [persistence] Use 'getStateAs()' instead of type casting
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
Labels: bug, persistence

#1942 Fixed first startup: Let StartLevelService only start once its configuration is available
  bundles/org.openhab.core/src/main/java/org/openhab/core/service/StartLevelService.java
Labels: bug

#1940 [automation] Make quantity types available in scripts
  bundles/org.openhab.core.model.rule/bnd.bnd
  bundles/org.openhab.core.model.script/bnd.bnd
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/scoping/ScriptImportSectionNamespaceScopeProvider.java
  itests/org.openhab.core.model.script.tests/src/main/java/org/openhab/core/model/script/engine/ScriptEngineOSGiTest.java
Labels: automation, bug

#1948 [automation] Fixed NPE by not calling 'toString()' on parameters passed to a logger
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/ScriptConditionHandler.java
Labels: automation, bug

#1952 [automation] Correctly return the evaluation result of DSL scripts
  bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java
Labels: automation, bug

#1947 [automation] Temporarily hide Binding ThingActions in UIs
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/module/provider/AnnotationActionModuleTypeHelper.java
Labels: UI, automation

#1950 [automation] Fixed startup rules being triggered more than once
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/SystemTriggerHandler.java
Labels: automation, bug

#1953 Introduce ready marker to correctly set start level 80
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
Labels: bug

#1960 [automation] Reintroduce delayed rule initialization
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
Labels: automation, bug

#1962 [automation] Correctly trigger rules with start level 50 trigger
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
Labels: automation, bug

#1963 Fix CORS header to allow preflight requests with authorization payload
  bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/filter/CorsFilter.java
  bundles/org.openhab.core.io.rest/src/test/java/org/openhab/core/io/rest/internal/filter/CorsFilterTest.java
Labels: bug

#1968 Do not consider disabled things for start level 80
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
Labels: automation, bug, critical

#1971 Fixed spelling of german laundry tag synonyms
  bundles/org.openhab.core.semantics/src/main/resources/tags_de.properties
Labels: bug

#1970 [automation] Added ItemStateUpdate action
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/factory/CoreModuleHandlerFactory.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemStateUpdateActionHandler.java
  bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/ItemActions.json
Labels: automation, enhancement

#1985 Fixed NPE in ScriptError if INode is empty
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/engine/ScriptError.java
Labels: DSL, bug

#1992 [chart] Harden ChartServlet against NPEs when no 'period' parameter is given
  bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/ChartServlet.java
Labels: bug

#2003 Updated rule dsl filename to rule uid mapping
  bundles/org.openhab.core.model.rule.runtime/src/org/openhab/core/model/rule/runtime/internal/DSLRuleProvider.java
Labels: automation, enhancement

#1965 [transport.modbus] Added support for RTU encoding over TCP
  bundles/org.openhab.core.io.transport.modbus/pom.xml
  bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/endpoint/ModbusTCPSlaveEndpoint.java
  bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/pooling/ModbusSlaveConnectionFactoryImpl.java
  bundles/org.openhab.core.io.transport.modbus/src/test/java/org/openhab/core/io/transport/modbus/test/IntegrationTestSupport.java
  bundles/org.openhab.core.io.transport.modbus/src/test/java/org/openhab/core/io/transport/modbus/test/ModbusSlaveEndpointTestCase.java
  bundles/org.openhab.core.io.transport.modbus/src/test/java/org/openhab/core/io/transport/modbus/test/SmokeTest.java
Labels: enhancement

#2009 Expire group item states
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ExpireManager.java
Labels: bug

#2018 Align all threads to naming convention
  bundles/org.openhab.core/src/main/java/org/openhab/core/common/QueueingThreadPoolExecutor.java
Labels: enhancement

#2020 Correctly handle file extension when looking up script
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/ScriptExecution.java
Labels: bug

#2036 [Persistence Extensions] Fixed varianceSince and deviationSince
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
  bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java
Labels: bug, persistence

#1984 [transport.modbus] Support dimensionless QuantityType commands.
  bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/ModbusBitUtilities.java
  bundles/org.openhab.core.io.transport.modbus/src/test/java/org/openhab/core/io/transport/modbus/test/BitUtilitiesCommandToRegistersTest.java
Labels: enhancement
