Repository openhab/openhab-core, pull requests merged in 2020-01, with the labels that each got.

#1316 Correction of unit spellings Ampere hour
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/SmartHomeUnits.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/SmartHomeUnitsTest.java
Labels: UoM

#1307 [rest] Suppress error message in REST response
  bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/JSONResponse.java
Labels: REST/SSE

#1291 [mqtt] Keep track of retained messages
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnection.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/ClientCallback.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/Subscription.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/TopicSubscribers.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/client/Mqtt3AsyncClientWrapper.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/client/Mqtt5AsyncClientWrapper.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/client/MqttAsyncClientWrapper.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/sslcontext/AcceptAllCertificatesSSLContext.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/sslcontext/CustomSSLContextProvider.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/sslcontext/SSLContextProvider.java
  bundles/org.openhab.core.io.transport.mqtt/src/test/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnectionEx.java
  bundles/org.openhab.core.io.transport.mqtt/src/test/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnectionTests.java
  bundles/org.openhab.core.io.transport.mqtt/src/test/java/org/openhab/core/io/transport/mqtt/internal/MqttServiceTests.java
  bundles/org.openhab.core.io.transport.mqtt/src/test/java/org/openhab/core/io/transport/mqtt/internal/TopicSubscriberTests.java
Labels: enhancement

#1337 [persistence] Added test coverage for persistence extension
  bundles/org.openhab.core.model.persistence/src/org/openhab/core/model/persistence/extensions/PersistenceExtensions.java
  itests/org.openhab.core.model.persistence.tests/src/main/java/org/openhab/core/model/persistence/extensions/PersistenceExtensionsTest.java
  itests/org.openhab.core.model.persistence.tests/src/main/java/org/openhab/core/model/persistence/tests/TestPersistenceService.java
Labels: test

#1338 [persistence] Fixed JavaDoc for persistence extension
  bundles/org.openhab.core.model.persistence/src/org/openhab/core/model/persistence/extensions/PersistenceExtensions.java
Labels: documentation

#1342 replaced Joda Time by Java Time
  bom/compile/pom.xml
  bom/runtime/pom.xml
  bundles/org.openhab.core.model.persistence/NOTICE
  bundles/org.openhab.core.model.persistence/bnd.bnd
  bundles/org.openhab.core.model.persistence/pom.xml
  bundles/org.openhab.core.model.persistence/src/org/openhab/core/model/persistence/extensions/PersistenceExtensions.java
  bundles/org.openhab.core.model.rule/bnd.bnd
  bundles/org.openhab.core.model.script/bnd.bnd
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/ScriptExecution.java
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Timer.java
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/actions/TimerImpl.java
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/scoping/ScriptImplicitlyImportedTypes.java
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/scoping/ScriptImportSectionNamespaceScopeProvider.java
  features/karaf/openhab-tp/src/main/feature/feature.xml
  itests/org.openhab.core.model.core.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.persistence.tests/itest.bndrun
  itests/org.openhab.core.model.persistence.tests/src/main/java/org/openhab/core/model/persistence/extensions/PersistenceExtensionsTest.java
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/src/main/java/org/openhab/core/model/script/actions/ScriptExecutionTest.java
  itests/org.openhab.core.model.script.tests/src/main/java/org/openhab/core/model/script/scheduler/test/MockClosure.java
  itests/org.openhab.core.model.thing.tests/itest.bndrun
Labels: API breaking
