Repository openhab/openhab-core, pull requests merged in 2021-04, with the labels that each got.

#2272 [modbus] Workaround for nrjavaserial issues: do not disconnect serial
  bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/ModbusManagerImpl.java
Labels: bug

#2125 Added rule rest endpoint and backend operation for rule execution simulation
  bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/RuleResource.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/RuleExecution.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/RuleManager.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/handler/TimeBasedConditionHandler.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/handler/TimeBasedTriggerHandler.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleExecutionSimulator.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/DayOfWeekConditionHandler.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/EphemerisConditionHandler.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GenericCronTriggerHandler.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/TimeOfDayConditionHandler.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/TimeOfDayTriggerHandler.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/scheduler/CronSchedulerImpl.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/scheduler/CronAdjuster.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/internal/scheduler/CronAdjusterMiscTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/internal/scheduler/CronAdjusterTest.java
  itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/RuleSimulationTest.java
Labels: REST/SSE, automation

#2292 Upgrade org.apache.servicemix.specs.activation-api-1.2.1 to fix mail sending
  bom/runtime/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
Labels: bug

#2294 French translation added for signal strength options
  bundles/org.openhab.core.thing/src/main/resources/OH-INF/i18n/DefaultSystemChannels_fr.properties
Labels: translation

#2297 [i18n] Added i18n properties files for DefaultSystemChannels and Profiles
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/units.properties
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/DefaultSystemChannelTypeProvider.java
  bundles/org.openhab.core.thing/src/main/resources/OH-INF/config/firmware.xml
  bundles/org.openhab.core.thing/src/main/resources/OH-INF/i18n/DefaultSystemChannels.properties
  bundles/org.openhab.core.thing/src/main/resources/OH-INF/i18n/SystemProfiles.properties
  bundles/org.openhab.core/src/main/resources/OH-INF/config/network.xml
Labels: i18n/l10n

#2295 [i18n] Added unit test for UTF-8 encoded properties
  itests/org.openhab.core.tests/src/main/java/org/openhab/core/internal/i18n/TranslationProviderOSGiTest.java
  itests/org.openhab.core.tests/src/main/resources/OH-INF/i18n/otherResourceName_de_AT.properties
  itests/org.openhab.core.tests/src/main/resources/OH-INF/i18n/otherResourceName_en.properties
Labels: i18n/l10n

#2300 Remove trailing space from update-canceled in firmware.properties
  bundles/org.openhab.core.thing/src/main/resources/OH-INF/i18n/firmware.properties
Labels: translation

#2302 Fix Crowdin translation filename mismatch
  crowdin.yml
Labels: i18n/l10n

#2307 [net] Filter duplicate broadcast addresses for service configuration if multiple network interfaces are available
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/net/NetworkConfigOptionProvider.java
Labels: enhancement

#2318 [REST] Added editable flag for ItemChannelLinks by introducing an EnrichedItemChannelLinkDTO
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/link/ItemChannelLinkResource.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/link/EnrichedItemChannelLinkDTO.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/link/EnrichedItemChannelLinkDTOMapper.java
  itests/org.openhab.core.io.rest.core.tests/src/main/java/org/openhab/core/io/rest/core/internal/link/ItemChannelLinkResourceOSGiTest.java
Labels: REST/SSE, enhancement

#2289 [metering] Fix dependency issue in io.monitor bundle (#2288)
  bundles/org.openhab.core.io.monitor/bnd.bnd
  bundles/org.openhab.core.io.monitor/pom.xml
  bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/metrics/RuleMetric.java
Labels: bug

#2327 Upgrade hivemq-mqtt-client to 1.2.2, Netty to 4.1.63.Final
  bom/compile/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
Labels: dependencies, enhancement

#2306 [i18n] Translation of configurable services
  bundles/org.openhab.core.audio/src/main/resources/OH-INF/config/audio.xml
  bundles/org.openhab.core.audio/src/main/resources/OH-INF/i18n/audio.properties
  bundles/org.openhab.core.config.discovery/src/main/resources/OH-INF/config/inbox.xml
  bundles/org.openhab.core.config.discovery/src/main/resources/OH-INF/i18n/inbox.properties
  bundles/org.openhab.core.ephemeris/src/main/resources/OH-INF/config/ephemeris.xml
  bundles/org.openhab.core.ephemeris/src/main/resources/OH-INF/i18n/ephemeris.properties
  bundles/org.openhab.core.io.rest.auth/src/main/resources/OH-INF/config/restauth.xml
  bundles/org.openhab.core.io.rest.auth/src/main/resources/OH-INF/i18n/restauth.properties
  bundles/org.openhab.core.karaf/src/main/resources/OH-INF/config/addons.xml
  bundles/org.openhab.core.karaf/src/main/resources/OH-INF/i18n/addons.properties
  bundles/org.openhab.core.persistence/src/main/resources/OH-INF/config/persistence.xml
  bundles/org.openhab.core.persistence/src/main/resources/OH-INF/i18n/persistence.properties
  bundles/org.openhab.core.storage.json/src/main/resources/OH-INF/config/jsonStorage.xml
  bundles/org.openhab.core.storage.json/src/main/resources/OH-INF/i18n/jsonStorage.properties
  bundles/org.openhab.core.ui/src/main/resources/OH-INF/config/chart.xml
  bundles/org.openhab.core.ui/src/main/resources/OH-INF/i18n/chart.properties
  bundles/org.openhab.core.voice/src/main/resources/OH-INF/config/voice.xml
  bundles/org.openhab.core.voice/src/main/resources/OH-INF/i18n/voice.properties
  bundles/org.openhab.core/src/main/resources/OH-INF/config/i18n.xml
  bundles/org.openhab.core/src/main/resources/OH-INF/config/network.xml
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/i18n.properties
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/network.properties
Labels: i18n/l10n
