Repository openhab/openhab-core, pull requests merged in 2021-01, with the labels that each got.

#2049 Prevent errors in log when client closes the HTTP connection
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/GsonMessageBodyWriter.java
Labels: bug

#2052 [transformation] Added method to read all files with specific extensions in 'transform/' folder
  bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/AbstractFileTransformationService.java
Labels: enhancement

#2059 Include group label in warn log message
  bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java
Labels: enhancement

#2057 [automation] Cache parsed script in order to improve performance
  bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java
Labels: automation, enhancement

#2050 Extended serial port implementation
  bundles/org.openhab.core.io.transport.serial.javacomm/src/main/java/org/openhab/core/io/transport/serial/internal/SerialPortImpl.java
  bundles/org.openhab.core.io.transport.serial.rxtx/src/main/java/org/openhab/core/io/transport/serial/rxtx/RxTxSerialPort.java
  bundles/org.openhab.core.io.transport.serial/src/main/java/org/openhab/core/io/transport/serial/SerialPort.java
Labels: enhancement

#2077 [automation] Avoid disappearing rules by correctly checking the model and its type
  bundles/org.openhab.core.model.rule.runtime/src/org/openhab/core/model/rule/runtime/internal/DSLRuleProvider.java
Labels: automation, bug

#2029 Added unit tests for check if persistence extension returns QuantityType if persistence service returns QuantityType
  bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java
  bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/TestPersistenceService.java
Labels: test

#2087 Moved 'NumberExtensionsTest' from itest to pure unit test and merged redundant calsses
  bundles/org.openhab.core.model.script/src.moved/test/java/org/openhab/core/model/script/lib/NumberExtensionsTest.java
  itests/org.openhab.core.model.script.tests/src/main/java/org/openhab/core/model/script/lib/NumberExtensionsTest.java
Labels: test

#2093 Fix unstable tests due to RuleEngine not being started
  itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationJsonTest.java
  itests/org.openhab.core.automation.module.core.tests/itest.bndrun
  itests/org.openhab.core.automation.module.core.tests/src/main/java/org/openhab/core/automation/internal/module/RunRuleModuleTest.java
  itests/org.openhab.core.automation.module.core.tests/src/main/java/org/openhab/core/automation/internal/module/RuntimeRuleTest.java
  itests/org.openhab.core.automation.module.timer.tests/itest.bndrun
  itests/org.openhab.core.automation.module.timer.tests/src/main/java/org/openhab/core/automation/module/timer/internal/BasicConditionHandlerTest.java
  itests/org.openhab.core.automation.module.timer.tests/src/main/java/org/openhab/core/automation/module/timer/internal/RuntimeRuleTest.java
  itests/org.openhab.core.automation.tests/itest.bndrun
  itests/org.openhab.core.automation.tests/src/main/java/org/openhab/core/automation/event/RuleEventTest.java
Labels: test

#2104 Also return command line execution result in case of error return code
  bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/exec/ExecUtil.java
Labels: bug

#2120 Fix BOM dependency issues
  bom/runtime/pom.xml
  bom/test-index/pom.xml
  itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun
  itests/org.openhab.core.automation.integration.tests/itest.bndrun
  itests/org.openhab.core.automation.module.core.tests/itest.bndrun
  itests/org.openhab.core.automation.module.script.tests/itest.bndrun
  itests/org.openhab.core.automation.module.timer.tests/itest.bndrun
  itests/org.openhab.core.automation.tests/itest.bndrun
  itests/org.openhab.core.binding.xml.tests/itest.bndrun
  itests/org.openhab.core.config.core.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun
  itests/org.openhab.core.config.dispatch.tests/itest.bndrun
  itests/org.openhab.core.config.xml.tests/itest.bndrun
  itests/org.openhab.core.ephemeris.tests/itest.bndrun
  itests/org.openhab.core.io.rest.core.tests/itest.bndrun
  itests/org.openhab.core.model.core.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
  itests/org.openhab.core.storage.json.tests/itest.bndrun
  itests/org.openhab.core.tests/itest.bndrun
  itests/org.openhab.core.thing.tests/itest.bndrun
  itests/org.openhab.core.thing.xml.tests/itest.bndrun
  itests/org.openhab.core.voice.tests/itest.bndrun
Labels: infrastructure

#2114 [executeCommandLine] should return STDERR if STDOUT is empty
  bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/exec/ExecUtil.java
  bundles/org.openhab.core.io.net/src/test/java/org/openhab/core/io/net/exec/ExecUtilTest.java
Labels: bug

#2157 Added system default channel type to control color temperature in Kelvin
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/DefaultSystemChannelTypeProvider.java
  bundles/org.openhab.core.thing/src/main/resources/OH-INF/i18n/DefaultSystemChannels_de.properties
  bundles/org.openhab.core.thing/src/main/resources/OH-INF/i18n/DefaultSystemChannels_fr.properties
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/SystemWideChannelTypesTest.java
Labels: enhancement

#2155 [jsondb] Restore zero byte files from backup
  bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/JsonStorage.java
Labels: enhancement

#2147 [timer] Add Timer.getExecutionTime()
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Timer.java
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/actions/TimerImpl.java
Labels: enhancement

#2153 [timer] Fix to allow timer reschedule after termination
  bundles/org.openhab.core.model.script/src.moved/test/java/org/openhab/core/model/script/internal/actions/TimerImplTest.java
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/actions/TimerImpl.java
Labels: bug

#1884 [automation] Script dependency tracking
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/DependencyTracker.java
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileWatcher.java
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptLibraryWatcher.java
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/collection/BidiSetBag.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptDependencyListener.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptEngineFactory.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptEngineManager.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java
Labels: automation, enhancement

#1897 Add ability for scripts to create unmanaged rules
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/shared/ScriptedAutomationManager.java
Labels: automation, enhancement

#2165 Fix changing temperature via BasicUI (#2091)
  bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java
  bundles/org.openhab.core.ui/src/test/java/org/openhab/core/ui/internal/items/ItemUIRegistryImplTest.java
Labels: bug
