Repository openhab/openhab-core, pull requests merged in 2021-11, with the labels that each got.

#2552 Exclude logback-classic from org.apache.aries.jax.rs.whiteboard
  bom/test/pom.xml
Labels: test

#2533 Align item endpoint with items endpoint
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java
  itests/org.openhab.core.io.rest.core.tests/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResourceOSGiTest.java
Labels: enhancement, REST/SSE

#2555 [profile] Removed failing timestamp offset test
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/TimestampOffsetProfileTest.java
Labels: test

#2551 WebClientFactoryImpl deprecation and blocking test fixes
  bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/internal/WebClientFactoryImpl.java
  bundles/org.openhab.core.io.net/src/test/java/org/openhab/core/io/net/http/internal/WebClientFactoryImplTest.java
Labels: test

#2547 mDNS / UPnP discovery internationalization
  bundles/org.openhab.core.config.discovery.mdns/src/main/java/org/openhab/core/config/discovery/mdns/internal/MDNSDiscoveryService.java
  bundles/org.openhab.core.config.discovery.upnp/src/main/java/org/openhab/core/config/discovery/upnp/internal/UpnpDiscoveryService.java
  bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractDiscoveryService.java
  bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/AbstractDiscoveryServiceTest.java
Labels: enhancement, i18n/l10n

#2557 GitHub Actions workflow improvements
  .github/scripts/maven-build
  .github/workflows/ci-build.yml
Labels: infrastructure

#2560 Suppress bnd warnings for unused imports/exports
  pom.xml
Labels: infrastructure

#2563 Fix NPE in WatchQueueReader
  bundles/org.openhab.core/src/main/java/org/openhab/core/service/WatchQueueReader.java
Labels: bug

#2549 New exception class that incorporates support for internationalization
  bundles/org.openhab.core/src/main/java/org/openhab/core/i18n/AbstractI18nException.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/i18n/CommunicationException.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/i18n/ConfigurationException.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/i18n/ConnectionException.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/internal/i18n/I18nExceptionTest.java
Labels: enhancement, i18n/l10n

#2565 Make LifecycleScriptExtensionProvider and its Disposable interface public
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/LifecycleScriptExtensionProvider.java
Labels: enhancement, automation

#2531 Prevent shutdown of shared thread pool
  bundles/org.openhab.core/src/main/java/org/openhab/core/common/ThreadPoolManager.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/common/ThreadPoolManagerTest.java
Labels: enhancement

#2561 Use POM packaging with index BOMs
  bom/openhab-core-index/pom.xml
  bom/runtime-index/pom.xml
  bom/test-index/pom.xml
Labels: infrastructure

#2569 [test] Added Magic Button triggering some events every 5 seconds
  bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/MagicBindingConstants.java
  bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/handler/MagicButtonHandler.java
  bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/handler/MagicRollershutterHandler.java
  bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/handler/MagicThermostatThingHandler.java
  bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/internal/MagicHandlerFactory.java
  bundles/org.openhab.core.test.magic/src/main/resources/OH-INF/i18n/magic.properties
  bundles/org.openhab.core.test.magic/src/main/resources/OH-INF/i18n/magic_de.properties
  bundles/org.openhab.core.test.magic/src/main/resources/OH-INF/i18n/magic_en.properties
  bundles/org.openhab.core.test.magic/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.core.test.magic/src/main/resources/OH-INF/thing/thing-types.xml
Labels: test

#2572 Update Jackson to 2.12.5
  bom/runtime/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
Labels: dependencies

#2573 Upgrade UoM dependencies
  bom/compile/pom.xml
  bom/runtime/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
  itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun
  itests/org.openhab.core.automation.integration.tests/itest.bndrun
  itests/org.openhab.core.automation.module.core.tests/itest.bndrun
  itests/org.openhab.core.automation.module.script.tests/itest.bndrun
  itests/org.openhab.core.automation.module.timer.tests/itest.bndrun
  itests/org.openhab.core.automation.tests/itest.bndrun
  itests/org.openhab.core.binding.xml.tests/itest.bndrun
  itests/org.openhab.core.config.core.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun
  itests/org.openhab.core.config.dispatch.tests/itest.bndrun
  itests/org.openhab.core.config.xml.tests/itest.bndrun
  itests/org.openhab.core.ephemeris.tests/itest.bndrun
  itests/org.openhab.core.io.rest.core.tests/itest.bndrun
  itests/org.openhab.core.model.core.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
  itests/org.openhab.core.storage.json.tests/itest.bndrun
  itests/org.openhab.core.tests/itest.bndrun
  itests/org.openhab.core.thing.tests/itest.bndrun
  itests/org.openhab.core.thing.xml.tests/itest.bndrun
  itests/org.openhab.core.voice.tests/itest.bndrun
Labels: UoM, dependencies

#2574 Upgrade JUnit and Mockito dependencies
  bom/test-index/pom.xml
  bom/test/pom.xml
  itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun
  itests/org.openhab.core.automation.integration.tests/itest.bndrun
  itests/org.openhab.core.automation.module.core.tests/itest.bndrun
  itests/org.openhab.core.automation.module.script.tests/itest.bndrun
  itests/org.openhab.core.automation.module.timer.tests/itest.bndrun
  itests/org.openhab.core.automation.tests/itest.bndrun
  itests/org.openhab.core.binding.xml.tests/itest.bndrun
  itests/org.openhab.core.config.core.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun
  itests/org.openhab.core.config.dispatch.tests/itest.bndrun
  itests/org.openhab.core.config.xml.tests/itest.bndrun
  itests/org.openhab.core.ephemeris.tests/itest.bndrun
  itests/org.openhab.core.io.rest.core.tests/itest.bndrun
  itests/org.openhab.core.model.core.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
  itests/org.openhab.core.storage.json.tests/itest.bndrun
  itests/org.openhab.core.tests/itest.bndrun
  itests/org.openhab.core.thing.tests/itest.bndrun
  itests/org.openhab.core.thing.xml.tests/itest.bndrun
  itests/org.openhab.core.voice.tests/itest.bndrun
Labels: test, dependencies

#2570 Add Timer.isCancelled() method
  bundles/org.openhab.core.model.script/src.moved/test/java/org/openhab/core/model/script/internal/actions/TimerImplTest.java
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Timer.java
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/actions/TimerImpl.java
Labels: enhancement

#2579 Fix ConcurrentModificationException in ExpiringUserSecurityContextCache
  bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/ExpiringUserSecurityContextCache.java
  bundles/org.openhab.core.io.rest.auth/src/test/java/org/openhab/core/io/rest/auth/internal/ExpiringUserSecurityContextCacheTest.java
Labels: bug

#2582 Use Maven 3.8.4 in GHA CI builds
  .github/workflows/ci-build.yml
Labels: infrastructure

#2583 Update bnd to 6.1.0
  itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun
  itests/org.openhab.core.automation.integration.tests/itest.bndrun
  itests/org.openhab.core.automation.module.core.tests/itest.bndrun
  itests/org.openhab.core.automation.module.script.tests/itest.bndrun
  itests/org.openhab.core.automation.module.timer.tests/itest.bndrun
  itests/org.openhab.core.automation.tests/itest.bndrun
  itests/org.openhab.core.binding.xml.tests/itest.bndrun
  itests/org.openhab.core.config.core.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun
  itests/org.openhab.core.config.dispatch.tests/itest.bndrun
  itests/org.openhab.core.config.xml.tests/itest.bndrun
  itests/org.openhab.core.ephemeris.tests/itest.bndrun
  itests/org.openhab.core.io.rest.core.tests/itest.bndrun
  itests/org.openhab.core.model.core.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
  itests/org.openhab.core.storage.json.tests/itest.bndrun
  itests/org.openhab.core.tests/itest.bndrun
  itests/org.openhab.core.thing.tests/itest.bndrun
  itests/org.openhab.core.thing.xml.tests/itest.bndrun
  itests/org.openhab.core.voice.tests/itest.bndrun
  pom.xml
Labels: infrastructure

#2577 Fix IllegalStateException in IconServlet
  bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/internal/IconServlet.java
Labels: bug
