Repository openhab/openhab-core, pull requests merged in 2021-05, with the labels that each got.

#2329 Remove commons-io and commons-codec dependencies
  bom/compile/pom.xml
  bom/runtime/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
Labels: awaiting other PR, dependencies

#2337 [automation] match on complete channel UID
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ChannelEventTriggerHandler.java
  bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/handler/ChannelEventTriggerHandlerTest.java
Labels: automation, bug

#2333 [i18n] Added i18n feature for labels of ConfigurableServices
  bundles/org.openhab.core.audio/src/main/resources/OH-INF/i18n/audio.properties
  bundles/org.openhab.core.config.discovery/src/main/resources/OH-INF/i18n/inbox.properties
  bundles/org.openhab.core.ephemeris/src/main/resources/OH-INF/i18n/ephemeris.properties
  bundles/org.openhab.core.io.rest.auth/src/main/resources/OH-INF/i18n/restauth.properties
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/service/ConfigurableServiceResource.java
  bundles/org.openhab.core.karaf/src/main/resources/OH-INF/i18n/addons.properties
  bundles/org.openhab.core.persistence/src/main/resources/OH-INF/i18n/persistence.properties
  bundles/org.openhab.core.storage.json/src/main/resources/OH-INF/i18n/jsonStorage.properties
  bundles/org.openhab.core.ui/src/main/resources/OH-INF/i18n/chart.properties
  bundles/org.openhab.core.voice/src/main/resources/OH-INF/i18n/voice.properties
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/i18n.properties
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/network.properties
Labels: enhancement, i18n/l10n

#2347 [magic] Added Channel for DateTime Item
  bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/handler/MagicOnOffLightHandler.java
  bundles/org.openhab.core.test.magic/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.core.test.magic/src/main/resources/OH-INF/thing/thing-types.xml
Labels: test

#2348 Implement hostnameValidated flag for secure MQTT connections
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnection.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnectionConfig.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/MqttServiceImpl.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/client/Mqtt3AsyncClientWrapper.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/client/Mqtt5AsyncClientWrapper.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/client/MqttAsyncClientWrapper.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/resources/OH-INF/config/brokerConnectionInstance.xml
  bundles/org.openhab.core.io.transport.mqtt/src/main/resources/OH-INF/i18n/brokerConnectionInstance.properties
  bundles/org.openhab.core.io.transport.mqtt/src/test/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnectionEx.java
  bundles/org.openhab.core.io.transport.mqtt/src/test/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnectionTests.java
  bundles/org.openhab.core.io.transport.mqtt/src/test/java/org/openhab/core/io/transport/mqtt/internal/MqttServiceTests.java
Labels: enhancement

#2319 Upgrade Units of Measurement dependencies
  bom/compile/pom.xml
  bom/runtime/pom.xml
  bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemHysteresisStateProfile.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemRangeStateProfile.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityTypeArithmeticGroupFunction.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/BinaryPrefix.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/CustomUnits.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/ImperialUnits.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/MetricPrefix.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/SIUnits.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/Units.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/types/util/UnitUtils.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/dimension/VolumetricFlowRateTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeArithmeticGroupFunctionTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/UnitsTest.java
  features/karaf/openhab-tp/src/main/feature/feature.xml
  itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun
  itests/org.openhab.core.automation.integration.tests/itest.bndrun
  itests/org.openhab.core.automation.module.core.tests/itest.bndrun
  itests/org.openhab.core.automation.module.script.tests/itest.bndrun
  itests/org.openhab.core.automation.module.timer.tests/itest.bndrun
  itests/org.openhab.core.automation.tests/itest.bndrun
  itests/org.openhab.core.binding.xml.tests/itest.bndrun
  itests/org.openhab.core.config.core.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun
  itests/org.openhab.core.config.dispatch.tests/itest.bndrun
  itests/org.openhab.core.config.xml.tests/itest.bndrun
  itests/org.openhab.core.ephemeris.tests/itest.bndrun
  itests/org.openhab.core.io.rest.core.tests/itest.bndrun
  itests/org.openhab.core.model.core.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/src/main/java/org/openhab/core/model/script/engine/ScriptEngineOSGiTest.java
  itests/org.openhab.core.model.thing.tests/itest.bndrun
  itests/org.openhab.core.storage.json.tests/itest.bndrun
  itests/org.openhab.core.tests/itest.bndrun
  itests/org.openhab.core.tests/src/main/java/org/openhab/core/items/GroupItemOSGiTest.java
  itests/org.openhab.core.thing.tests/itest.bndrun
  itests/org.openhab.core.thing.xml.tests/itest.bndrun
  itests/org.openhab.core.voice.tests/itest.bndrun
Labels: UoM, dependencies, enhancement

#2358 Fix unstable MqttBrokerConnectionTests
  bundles/org.openhab.core.io.transport.mqtt/src/test/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnectionTests.java
Labels: test

#2354 Fix unstable CronSchedulerImplTest
  bundles/org.openhab.core/src/test/java/org/openhab/core/internal/scheduler/CronSchedulerImplTest.java
Labels: test

#2356 Update Swagger to 2.1.9
  bom/compile/pom.xml
  bom/runtime/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
Labels: dependencies

#2357 Update Jackson to 2.12.3
  bom/runtime/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
Labels: dependencies

#2359 Fix JavaDoc build by upgrading plexus-java dependency
  pom.xml
Labels: documentation

#2349 Display raw item state when formatting fails
  bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/SseItemStatesEventBuilder.java
Labels: bug

#2361 Expose Channel Type UIDs of default System Channel Types
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/DefaultSystemChannelTypeProvider.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/SystemWideChannelTypesTest.java
Labels: enhancement

#2351 [profiles] Added "timestamp-offset" Profile
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/i18n/I18nConfigOptionsProvider.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemOffsetProfile.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemProfileFactory.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/TimestampOffsetProfile.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/profiles/SystemProfiles.java
  bundles/org.openhab.core.thing/src/main/resources/OH-INF/config/timestampOffsetProfile.xml
  bundles/org.openhab.core.thing/src/main/resources/OH-INF/i18n/SystemProfiles.properties
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/SystemOffsetProfileTest.java
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/TimestampOffsetProfileTest.java
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/TimestampProfileTest.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/profiles/SystemProfileFactoryOSGiTest.java
Labels: enhancement

#2367 [UoM] Catch MeasurementParseException in UnitUtils.parseUnit(String) method
  bundles/org.openhab.core/src/main/java/org/openhab/core/types/util/UnitUtils.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/types/util/UnitUtilsTest.java
Labels: UoM

#2363 Upgrade to Karaf 4.3.2
  bom/compile/pom.xml
  bom/runtime/pom.xml
  features/karaf/openhab-core/pom.xml
  features/karaf/openhab-tp/pom.xml
  itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun
  itests/org.openhab.core.automation.integration.tests/itest.bndrun
  itests/org.openhab.core.automation.module.core.tests/itest.bndrun
  itests/org.openhab.core.automation.module.script.tests/itest.bndrun
  itests/org.openhab.core.automation.module.timer.tests/itest.bndrun
  itests/org.openhab.core.automation.tests/itest.bndrun
  itests/org.openhab.core.binding.xml.tests/itest.bndrun
  itests/org.openhab.core.config.core.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun
  itests/org.openhab.core.config.dispatch.tests/itest.bndrun
  itests/org.openhab.core.config.xml.tests/itest.bndrun
  itests/org.openhab.core.ephemeris.tests/itest.bndrun
  itests/org.openhab.core.io.rest.core.tests/itest.bndrun
  itests/org.openhab.core.model.core.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
  itests/org.openhab.core.storage.json.tests/itest.bndrun
  itests/org.openhab.core.tests/itest.bndrun
  itests/org.openhab.core.thing.tests/itest.bndrun
  itests/org.openhab.core.thing.xml.tests/itest.bndrun
  itests/org.openhab.core.voice.tests/itest.bndrun
  pom.xml
Labels: dependencies, karaf

#2343 [REST] inbox/approve: new response code 400
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/discovery/InboxResource.java
Labels: REST/SSE, enhancement

#2330 [modbus] clearer error messages
  bundles/org.openhab.core.io.transport.modbus/pom.xml
Labels: enhancement

#2353 [profiles] Remove update of timestamp on Change/Update for Item update
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/TimestampChangeProfile.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/TimestampUpdateProfile.java
  bundles/org.openhab.core.thing/src/main/resources/OH-INF/i18n/SystemProfiles.properties
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/TimestampProfileTest.java
Labels: bug

#2369 Upgrade XStream to 1.4.17
  bom/compile/pom.xml
  bom/runtime/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
  itests/org.openhab.core.binding.xml.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.tests/itest.bndrun
  itests/org.openhab.core.config.xml.tests/itest.bndrun
  itests/org.openhab.core.ephemeris.tests/itest.bndrun
  itests/org.openhab.core.model.core.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
  itests/org.openhab.core.thing.tests/itest.bndrun
  itests/org.openhab.core.thing.xml.tests/itest.bndrun
Labels: dependencies

#2365 Support parsing localized strings with DecimalType, PercentType and QuantityType
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DecimalType.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/PercentType.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/ItemStateConverterImplTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/DecimalTypeTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/PercentTypeTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeArithmeticGroupFunctionTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java
Labels: UoM, enhancement, i18n/l10n

#2373 [automation] Remove readOnly flag on script type parameter
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/provider/ScriptModuleTypeProvider.java
Labels: automation

#2364 Added "timestamp-trigger" Profile
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemProfileFactory.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/TimestampTriggerProfile.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/profiles/SystemProfiles.java
  bundles/org.openhab.core.thing/src/main/resources/OH-INF/i18n/SystemProfiles.properties
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/TimestampTriggerProfileTest.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/profiles/SystemProfileFactoryOSGiTest.java
Labels: enhancement

#2378 [automation] add tags to item modules
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemCommandActionHandler.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemStateUpdateActionHandler.java
  bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/ItemActions.json
  bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/ItemTriggers.json
Labels: automation

#2385 [test] Fixed warnings on missing representation properties
  itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/inbox/DynamicThingUpdateOSGiTest.java
  itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/internal/InboxOSGiTest.java
Labels: test

#2383 [config] Changed 'ConfigDescriptionParameterDTO' field serialization 'defaultValue' -> 'default'
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/FilterCriteria.java
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/dto/ConfigDescriptionDTOMapper.java
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/dto/ConfigDescriptionParameterDTO.java
  bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/dto/ConfigDescriptionDTOTest.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/config/ConfigDescriptionResource.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java
  bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/config/EnrichedConfigDescriptionDTOMapperTest.java
  bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/internal/config/ConfigDescriptionResourceTest.java
  itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationJsonTest.java
  itests/org.openhab.core.automation.integration.tests/src/main/resources/OH-INF/automation/moduletypes/CustomActionsTypeDefinition.json
Labels: API breaking, enhancement

#2391 Update to new JmDNS release 3.5.7
  bom/compile/pom.xml
  bom/runtime/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
  itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
Labels: dependencies
