Repository openhab/openhab-core, pull requests merged in 2022-11, with the labels that each got.

#3129 update system.color-temperature-abs channel type to be a Number:Temperature
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/DefaultSystemChannelTypeProvider.java
Labels: enhancement

#3137 Avoid parallel streams with common thread pool to avoid deadlocks
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/Subscription.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/AbstractLinkRegistry.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/ItemChannelLinkRegistry.java
Labels: bug

#3100 [voice] Allow stop single dialogs and start dialog on an existing processor
  bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java
  bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java
Labels: enhancement

#3144 Fix missing stateDescriptionProvider in Group items
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ItemRegistryImpl.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/GroupItem.java
  itests/org.openhab.core.tests/src/main/java/org/openhab/core/items/ItemRegistryImplTest.java
Labels: bug

#3157 Fix config normalization in ThingUpdatedEvent
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
Labels: bug

#3156 Add unmanaged scripts to rule registry
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/RuleManager.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
  bundles/org.openhab.core.model.rule.runtime/src/org/openhab/core/model/rule/runtime/internal/DSLRuleProvider.java
Labels: automation

#3154 [auth] Fix wrong parameter on AuthorizePageServlet
  bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/AuthorizePageServlet.java
Labels: bug

#3155 Refactor ScriptExecution to plain Java ScriptExtension
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/action/ScriptExecution.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/action/Timer.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/action/ScriptActionScriptScopeProvider.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/action/ScriptExecutionImpl.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/action/TimerImpl.java
  bundles/org.openhab.core.automation.module.script/src/test/java/org/openhab/core/automation/module/script/TimerImplTest.java
  bundles/org.openhab.core.model.script/bnd.bnd
  bundles/org.openhab.core.model.script/pom.xml
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/ScriptExecution.java
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/engine/action/ScriptExecutionActionService.java
Labels: enhancement, automation

#3153 Strip unit if NumberItem has no dimension
  bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/handler/ItemStateConditionHandlerTest.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/NumberItem.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/items/NumberItemTest.java
Labels: bug

#3143 Add default units for all dimensions
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/ImperialUnits.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/internal/i18n/I18nProviderImplTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/UnitsTest.java
Labels: bug

#3172 Fix createTimer for DSL rules
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/ScriptExecution.java
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Timer.java
Labels: bug, critical

#3170 tweak ScriptedRuleProvider slightly
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/shared/RuleSupportRuleRegistryDelegate.java
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/shared/ScriptedRuleProvider.java
Labels: enhancement

#3176 log full exception information when calling JSR223 scripts
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java
Labels: enhancement, automation

#3177 add QuantityType.toUnitRelative
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemOffsetProfile.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java
Labels: enhancement, UoM

#3168 Refactor script dependency tracking
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/DefaultScriptFileWatcher.java
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptLibraryWatcher.java
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/collection/BidiSetBag.java
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptDependencyTracker.java
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptFileWatcher.java
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/DependencyTracker.java
  bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptDependencyTrackerTest.java
  bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptFileWatcherTest.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptDependencyTracker.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptEngineFactory.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptEngineManager.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/factory/ScriptModuleHandlerFactory.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/AbstractScriptModuleHandler.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/ScriptActionHandler.java
  bundles/org.openhab.core.automation.module.script/src/test/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImplTest.java
Labels: bug, API breaking

#3180 wrap ScriptEngine executions in a SafeCaller
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java
  bundles/org.openhab.core.automation.module.script/src/test/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImplTest.java
Labels: bug

#3178 Fix transformRaw validation errors in DSL rules
  bundles/org.openhab.core.model.script/bnd.bnd
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Transformation.java
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/TransformationException.java
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/engine/action/TransformationActionService.java
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/scoping/ScriptImplicitlyImportedTypes.java
Labels: bug
