Repository openhab/openhab-core, pull requests merged in 2022-09, with the labels that each got.

#3075 Add visibility and color parameters to UI sitemap provider
  bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
Labels: enhancement

#3080 [rest] Check for an existing thing handler before updating config
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java
Labels: bug, REST/SSE

#3078 [tls] Rethrow 'IOException' instead of swallowing it
  bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/PEMTrustManager.java
Labels: enhancement

#3079 [thing] Added default channel types for electrical energy
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/DefaultSystemChannelTypeProvider.java
  bundles/org.openhab.core.thing/src/main/resources/OH-INF/i18n/DefaultSystemChannels.properties
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/SystemWideChannelTypesTest.java
Labels: enhancement

#3049 Improve FeatureInstaller
  bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java
  features/karaf/openhab-core/pom.xml
  features/karaf/openhab-core/src/main/feature/feature.xml
  features/karaf/openhab-tp/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
Labels: bug

#3072 Fix missing initial thing status event
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/events/ThingStatusInfoEvent.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/ThingManagerImplTest.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingManagerOSGiTest.java
Labels: bug

#2958 Normalize Metadata configuration from managed provider
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ManagedMetadataProviderImpl.java
Labels: bug

#3024 Normalize thing configuration before initialization
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
Labels: enhancement

#3085 Upgrade Californium to 2.7.3
  bom/compile/pom.xml
  bom/runtime/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
Labels: enhancement, dependencies

#3092 Fix StartLevelService "hanging" if config is changed.
  bundles/org.openhab.core/src/main/java/org/openhab/core/service/StartLevelService.java
Labels: bug

#3086 Support sending a keepalive packet to SSE item state connections
  bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/SseResource.java
Labels: enhancement, REST/SSE

#3095 Use identifier when rescheduling the timer
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/actions/TimerImpl.java
Labels: bug
