Repository openhab/openhab-core, pull requests merged in 2022-07, with the labels that each got.

#3029 Upgrade to JmDNS 3.5.8
  bom/runtime/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
  itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
Labels: dependencies

#3027 Add missing & refactor existing button toggle profiles
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/RawButtonTogglePlayerProfile.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/RawButtonToggleRollershutterProfile.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/RawButtonToggleSwitchProfile.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemProfileFactory.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/ToggleProfile.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/profiles/SystemProfiles.java
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/RawButtonToggleSwitchProfileTest.java
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/ToggleProfileTest.java
Labels: enhancement

#3035 Add default translations for automation module types
  bundles/org.openhab.core.automation/src/main/resources/OH-INF/i18n/automation.properties
Labels: translation

#3007 Log a warning when item for trigger/condition is missing or removed
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/factory/CoreModuleHandlerFactory.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GroupCommandTriggerHandler.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GroupStateTriggerHandler.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemCommandTriggerHandler.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemStateConditionHandler.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemStateTriggerHandler.java
  bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/handler/ItemStateConditionHandlerTest.java
Labels: enhancement

#3042 Fix marketplace add-on uninstall
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java
Labels: bug

#3045 Enrich distribution add-on with configDescriptionURI
  bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonService.java
Labels: enhancement

#2981 Wait for thing-type available in PersistentInbox
  bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/inbox/Inbox.java
  bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/PersistentInbox.java
  bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/internal/PersistentInboxTest.java
  itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/DiscoveryServiceRegistryOSGiTest.java
  itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/internal/InboxOSGiTest.java
  itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/test/DummyThingTypeProvider.java
Labels: enhancement

#2984 Allow bulk deletion of metadata
  bundles/org.openhab.core.io.console/src/main/java/org/openhab/core/io/console/internal/extension/MetadataConsoleCommandExtension.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java
Labels: enhancement, REST/SSE, karaf

#2970 Add REST support for deleting links and removing orphaned links
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/link/ItemChannelLinkResource.java
  bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/internal/link/ItemChannelLinkResourceTest.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/ItemChannelLinkRegistry.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/ManagedItemChannelLinkProvider.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/link/ItemChannelLinkOSGiTest.java
Labels: enhancement, REST/SSE
