Repository openhab/openhab-core, pull requests merged in 2022-03, with the labels that each got.

#2786 Upgrade Xtext/Xtend to 2.26.0, LSP4J to 0.12.0
  bom/compile-model/pom.xml
  bom/compile/pom.xml
  bom/runtime/pom.xml
  bundles/org.openhab.core.model.item/bnd.bnd
  bundles/org.openhab.core.model.item/pom.xml
  bundles/org.openhab.core.model.persistence/bnd.bnd
  bundles/org.openhab.core.model.persistence/pom.xml
  bundles/org.openhab.core.model.rule/bnd.bnd
  bundles/org.openhab.core.model.rule/pom.xml
  bundles/org.openhab.core.model.script/bnd.bnd
  bundles/org.openhab.core.model.script/pom.xml
  bundles/org.openhab.core.model.sitemap/bnd.bnd
  bundles/org.openhab.core.model.sitemap/pom.xml
  bundles/org.openhab.core.model.thing/bnd.bnd
  bundles/org.openhab.core.model.thing/pom.xml
  features/karaf/openhab-core/src/main/feature/feature.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
  itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun
  itests/org.openhab.core.automation.integration.tests/itest.bndrun
  itests/org.openhab.core.automation.module.core.tests/itest.bndrun
  itests/org.openhab.core.automation.module.script.tests/itest.bndrun
  itests/org.openhab.core.automation.module.timer.tests/itest.bndrun
  itests/org.openhab.core.automation.tests/itest.bndrun
  itests/org.openhab.core.binding.xml.tests/itest.bndrun
  itests/org.openhab.core.config.core.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun
  itests/org.openhab.core.config.dispatch.tests/itest.bndrun
  itests/org.openhab.core.config.xml.tests/itest.bndrun
  itests/org.openhab.core.ephemeris.tests/itest.bndrun
  itests/org.openhab.core.io.rest.core.tests/itest.bndrun
  itests/org.openhab.core.model.core.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
  itests/org.openhab.core.storage.json.tests/itest.bndrun
  itests/org.openhab.core.tests/itest.bndrun
  itests/org.openhab.core.thing.tests/itest.bndrun
  itests/org.openhab.core.thing.xml.tests/itest.bndrun
  itests/org.openhab.core.voice.tests/itest.bndrun
  pom.xml
Labels: enhancement, dependencies

#2817 Add Java 17 to GHA CI build matrix
  .github/workflows/ci-build.yml
  pom.xml
Labels: infrastructure

#2818 Correct GHA build step condition
  .github/workflows/ci-build.yml
Labels: infrastructure

#2820 Remove temporary OSGi framework inclusion
  itests/itest-include.bndrun
Labels: test

#2755 Fix missing STARTLEVEL_COMPLETE ReadyMarker
  bundles/org.openhab.core/src/main/java/org/openhab/core/service/StartLevelService.java
Labels: bug

#2775 Add more null annotations to XML processing classes
  bundles/org.openhab.core.binding.xml/src/main/java/org/openhab/core/binding/xml/internal/BindingInfoConverter.java
  bundles/org.openhab.core.binding.xml/src/main/java/org/openhab/core/binding/xml/internal/BindingInfoXmlResult.java
  bundles/org.openhab.core.config.xml/src/main/java/org/openhab/core/config/xml/ConfigDescriptionConverter.java
  bundles/org.openhab.core.config.xml/src/main/java/org/openhab/core/config/xml/ConfigDescriptionParameterConverter.java
  bundles/org.openhab.core.config.xml/src/main/java/org/openhab/core/config/xml/ConfigDescriptionParameterGroupConverter.java
  bundles/org.openhab.core.config.xml/src/main/java/org/openhab/core/config/xml/FilterCriteriaConverter.java
  bundles/org.openhab.core.config.xml/src/main/java/org/openhab/core/config/xml/util/ConverterAssertion.java
  bundles/org.openhab.core.config.xml/src/main/java/org/openhab/core/config/xml/util/ConverterAttributeMapValidator.java
  bundles/org.openhab.core.config.xml/src/main/java/org/openhab/core/config/xml/util/ConverterValueMap.java
  bundles/org.openhab.core.config.xml/src/main/java/org/openhab/core/config/xml/util/GenericUnmarshaller.java
  bundles/org.openhab.core.config.xml/src/main/java/org/openhab/core/config/xml/util/NodeAttributes.java
  bundles/org.openhab.core.config.xml/src/main/java/org/openhab/core/config/xml/util/NodeAttributesConverter.java
  bundles/org.openhab.core.config.xml/src/main/java/org/openhab/core/config/xml/util/NodeIterator.java
  bundles/org.openhab.core.config.xml/src/main/java/org/openhab/core/config/xml/util/NodeListConverter.java
  bundles/org.openhab.core.config.xml/src/main/java/org/openhab/core/config/xml/util/NodeName.java
  bundles/org.openhab.core.config.xml/src/main/java/org/openhab/core/config/xml/util/NodeValue.java
  bundles/org.openhab.core.config.xml/src/main/java/org/openhab/core/config/xml/util/NodeValueConverter.java
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistItemsJob.java
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/strategy/PersistenceCronStrategy.java
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/strategy/PersistenceStrategy.java
  bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/StorageEntryMapDeserializer.java
  bundles/org.openhab.core.thing.xml/src/main/java/org/openhab/core/thing/xml/internal/AbstractDescriptionTypeConverter.java
  bundles/org.openhab.core.thing.xml/src/main/java/org/openhab/core/thing/xml/internal/BridgeTypeConverter.java
  bundles/org.openhab.core.thing.xml/src/main/java/org/openhab/core/thing/xml/internal/BridgeTypeXmlResult.java
  bundles/org.openhab.core.thing.xml/src/main/java/org/openhab/core/thing/xml/internal/ChannelConverter.java
  bundles/org.openhab.core.thing.xml/src/main/java/org/openhab/core/thing/xml/internal/ChannelGroupTypeConverter.java
  bundles/org.openhab.core.thing.xml/src/main/java/org/openhab/core/thing/xml/internal/ChannelGroupTypeXmlResult.java
  bundles/org.openhab.core.thing.xml/src/main/java/org/openhab/core/thing/xml/internal/ChannelTypeConverter.java
  bundles/org.openhab.core.thing.xml/src/main/java/org/openhab/core/thing/xml/internal/ChannelTypeXmlResult.java
  bundles/org.openhab.core.thing.xml/src/main/java/org/openhab/core/thing/xml/internal/ChannelXmlResult.java
  bundles/org.openhab.core.thing.xml/src/main/java/org/openhab/core/thing/xml/internal/CommandDescriptionConverter.java
  bundles/org.openhab.core.thing.xml/src/main/java/org/openhab/core/thing/xml/internal/EventDescriptionConverter.java
  bundles/org.openhab.core.thing.xml/src/main/java/org/openhab/core/thing/xml/internal/ThingDescriptionConverter.java
  bundles/org.openhab.core.thing.xml/src/main/java/org/openhab/core/thing/xml/internal/ThingDescriptionList.java
  bundles/org.openhab.core.thing.xml/src/main/java/org/openhab/core/thing/xml/internal/ThingTypeConverter.java
  bundles/org.openhab.core.thing.xml/src/main/java/org/openhab/core/thing/xml/internal/ThingTypeXmlResult.java
  bundles/org.openhab.core.thing.xml/src/main/java/org/openhab/core/thing/xml/internal/XmlHelper.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/firmware/FirmwareRestriction.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/firmware/ParameterChecks.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/i18n/ThingTypeI18nUtil.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/AutoUpdatePolicy.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/ChannelGroupDefinition.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/CustomUnits.java
  itests/org.openhab.core.config.xml.tests/src/main/java/org/openhab/core/config/xml/test/BindingInstaller.java
Labels: API breaking

#2814 Add accepted types to ProfileContext
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ProfileContextImpl.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/profiles/ProfileContext.java
Labels: enhancement

#2835 [test] Fix PersistenceExtensionTest
  bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java
Labels: test

#2837 Run org.openhab.core tests in forks to reduce build time
  bundles/org.openhab.core/pom.xml
Labels: test

#2753 Fix exception during startup when kar is not yet loaded
  bundles/org.openhab.core.karaf/pom.xml
  bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java
Labels: bug

#2740 [discovery] keep format of thing properties
  bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/DiscoveryResult.java
  bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/DiscoveryResultImpl.java
  bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/PersistentInbox.java
  bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/internal/PersistentInboxTest.java
Labels: bug

#2825 [rest] Allow binary MediaType for RawType item states
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java
Labels: enhancement

#2829 Show config validation messages in thing status
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/BindingBaseClassesOSGiTest.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingManagerOSGiTest.java
Labels: enhancement

#2842 Remove MQTT system broker leftovers
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnectionConfig.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/MqttConnectionState.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/MqttService.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/MqttServiceObserver.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/MqttBrokerConnectionServiceInstance.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/MqttBrokerConnectionServiceInstanceMarker.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/MqttServiceImpl.java
  bundles/org.openhab.core.io.transport.mqtt/src/main/resources/OH-INF/config/brokerConnectionInstance.xml
  bundles/org.openhab.core.io.transport.mqtt/src/main/resources/OH-INF/i18n/brokerConnectionInstance.properties
  bundles/org.openhab.core.io.transport.mqtt/src/main/resources/OH-INF/i18n/brokerConnectionInstance_cs.properties
  bundles/org.openhab.core.io.transport.mqtt/src/main/resources/OH-INF/i18n/brokerConnectionInstance_de.properties
  bundles/org.openhab.core.io.transport.mqtt/src/main/resources/OH-INF/i18n/brokerConnectionInstance_el.properties
  bundles/org.openhab.core.io.transport.mqtt/src/main/resources/OH-INF/i18n/brokerConnectionInstance_fi.properties
  bundles/org.openhab.core.io.transport.mqtt/src/main/resources/OH-INF/i18n/brokerConnectionInstance_he.properties
  bundles/org.openhab.core.io.transport.mqtt/src/main/resources/OH-INF/i18n/brokerConnectionInstance_hu.properties
  bundles/org.openhab.core.io.transport.mqtt/src/main/resources/OH-INF/i18n/brokerConnectionInstance_it.properties
  bundles/org.openhab.core.io.transport.mqtt/src/main/resources/OH-INF/i18n/brokerConnectionInstance_nl.properties
  bundles/org.openhab.core.io.transport.mqtt/src/main/resources/OH-INF/i18n/brokerConnectionInstance_pt.properties
  bundles/org.openhab.core.io.transport.mqtt/src/main/resources/OH-INF/i18n/brokerConnectionInstance_ru.properties
  bundles/org.openhab.core.io.transport.mqtt/src/main/resources/OH-INF/i18n/brokerConnectionInstance_uk.properties
  bundles/org.openhab.core.io.transport.mqtt/src/main/resources/OH-INF/i18n/brokerConnectionInstance_zh.properties
  bundles/org.openhab.core.io.transport.mqtt/src/test/java/org/openhab/core/io/transport/mqtt/internal/MqttServiceTests.java
Labels: bug, API breaking

#2830 Fix ServiceException when add-on handlers are not fully initialized
  bundles/org.openhab.core.addon.marketplace.karaf/src/main/java/org/openhab/core/addon/marketplace/karaf/internal/community/CommunityKarafAddonHandler.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonService.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/MarketplaceAddonHandler.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityBundleAddonHandler.java
  bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/test/AbstractRemoteAddonServiceTest.java
  bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/test/TestAddonHandler.java
Labels: bug

#2811 [addonservices] Add version filtering
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonService.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/BundleVersion.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/model/AddonEntryDTO.java
  bundles/org.openhab.core.addon.marketplace/src/main/resources/OH-INF/config/marketplace.xml
  bundles/org.openhab.core.addon.marketplace/src/main/resources/OH-INF/i18n/marketplace.properties
  bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonServiceTest.java
  bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/marketplace/BundleVersionTest.java
  bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/marketplace/test/TestAddonHandler.java
  bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/marketplace/test/TestAddonService.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/addon/Addon.java
  bundles/org.openhab.core/src/main/resources/OH-INF/config/addons.xml
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/addons.properties
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/addons_cs.properties
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/addons_de.properties
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/addons_el.properties
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/addons_es.properties
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/addons_fi.properties
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/addons_fr.properties
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/addons_he.properties
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/addons_hu.properties
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/addons_it.properties
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/addons_nl.properties
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/addons_pl.properties
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/addons_pt.properties
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/addons_ru.properties
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/addons_uk.properties
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/addons_zh.properties
Labels: enhancement

#2868 Add missing default translations for add-ons/marketplace configuration options
  bundles/org.openhab.core.addon.marketplace/src/main/resources/OH-INF/i18n/marketplace.properties
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/addons.properties
Labels: translation

#2870 [rest] Improve description of REST API for deleting data from persistence
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResource.java
Labels: REST/SSE, documentation

#2866 Adding Indoor Temperature as system channel type
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/DefaultSystemChannelTypeProvider.java
  bundles/org.openhab.core.thing/src/main/resources/OH-INF/i18n/DefaultSystemChannels.properties
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/SystemWideChannelTypesTest.java
Labels: enhancement

#2859 Improve HostFragmentSupportTest
  itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/HostFragmentSupportTest.java
Labels: test
