Repository openhab/openhab-core, pull requests merged in 2022-02, with the labels that each got.

#2712 [config] Enable config validation for updates by handler
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandler.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/ThingHandlerCallback.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/BindingBaseClassesOSGiTest.java
Labels: enhancement

#2607 [addonservices] allow uninstalling of removed addons and fix other issues
  bundles/org.openhab.core.addon.marketplace/pom.xml
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonService.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/model/DiscourseCategoryResponseDTO.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/model/DiscourseTopicResponseDTO.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/model/AddonEntryDTO.java
  bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/test/AbstractRemoteAddonServiceTest.java
  bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/test/TestAddonHandler.java
  bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/test/TestAddonService.java
Labels: enhancement

#2728 [StandardInterpreter] add Spanish language
  bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/text/StandardInterpreter.java
Labels: enhancement, translation

#2736 fix recursive membership throws StackOverflowException on REST API call
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/item/EnrichedItemDTOMapper.java
  bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/item/EnrichedItemDTOMapperTest.java
Labels: bug, REST/SSE

#2738 Upgrade XStream to 1.4.19
  bom/compile/pom.xml
  bom/runtime/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
  itests/org.openhab.core.binding.xml.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.tests/itest.bndrun
  itests/org.openhab.core.config.xml.tests/itest.bndrun
  itests/org.openhab.core.ephemeris.tests/itest.bndrun
  itests/org.openhab.core.model.core.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
  itests/org.openhab.core.thing.tests/itest.bndrun
  itests/org.openhab.core.thing.xml.tests/itest.bndrun
  tools/i18n-plugin/pom.xml
Labels: dependencies, security

#2724 allow multiple listeners for same directory in WatchService
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/ScriptFileWatcher.java
  bundles/org.openhab.core.config.dispatch/src/main/java/org/openhab/core/config/dispatch/internal/ConfigDispatcherFileWatcher.java
  bundles/org.openhab.core.config.dispatch/src/test/java/org/openhab/core/config/dispatch/internal/ConfigDispatcherFileWatcherTest.java
  bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/internal/folder/FolderObserver.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/service/AbstractWatchService.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/service/WatchQueueReader.java
  itests/org.openhab.core.tests/src/test/java/service/AbstractWatchServiceTest.java
Labels: bug

#2735 fix removal of thing properties (single and bulk)
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandler.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/BindingBaseClassesOSGiTest.java
Labels: bug

#2691 [config] Add config validator for parameter options
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionParameterValidatorFactory.java
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionValidatorImpl.java
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/MessageKey.java
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/MinMaxValidator.java
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/OptionsValidator.java
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation.properties
  bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionValidatorTest.java
Labels: enhancement

#2746 Prevent JsonStorage backup corruption when disk is full
  bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/JsonStorage.java
Labels: bug

#2723 expose three classes used as bindings in JSR-223 rules as interfaces
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptExtensionManagerWrapper.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/defaultscope/ScriptBusEvent.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/defaultscope/ScriptThingActions.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptExtensionManagerWrapperImpl.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/DefaultScriptScopeProvider.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/ScriptBusEventImpl.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/ScriptThingActionsImpl.java
Labels: enhancement

#2731 [voice] New REST API to start/stop dialog processing
  bundles/org.openhab.core.io.rest.voice/src/main/java/org/openhab/core/io/rest/voice/internal/VoiceResource.java
Labels: enhancement, REST/SSE

#2759 Always run OSGi HTTP service on random port in itests
  itests/itest-include.bndrun
  itests/pom.xml
Labels: test, infrastructure

#2770 Avoid `URISyntaxException` in tests
  bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/ConfigUtilTest.java
  bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/dto/ConfigDescriptionDTOTest.java
  bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionValidatorTest.java
  bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/internal/PersistentInboxTest.java
  bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/internal/config/ConfigDescriptionResourceTest.java
  bundles/org.openhab.core.io.rest/src/test/java/org/openhab/core/io/rest/internal/filter/ProxyFilterTest.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/firmware/FirmwareUpdateServiceImpl.java
  bundles/org.openhab.core.ui/src/test/java/org/openhab/core/ui/internal/proxy/ProxyServletServiceTest.java
  itests/org.openhab.core.config.core.tests/src/main/java/org/openhab/core/config/core/ConfigOptionRegistryOSGiTest.java
  itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/internal/InboxOSGiTest.java
  itests/org.openhab.core.config.xml.tests/src/main/java/org/openhab/core/config/xml/test/ConfigDescriptionI18nTest.java
  itests/org.openhab.core.config.xml.tests/src/main/java/org/openhab/core/config/xml/test/ConfigDescriptionsTest.java
  itests/org.openhab.core.model.thing.testsupport/src/main/java/org/openhab/core/model/thing/testsupport/hue/TestHueConfigDescriptionProvider.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/BindingBaseClassesOSGiTest.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingManagerOSGiTest.java
  itests/org.openhab.core.thing.xml.tests/src/main/java/org/openhab/core/thing/xml/test/ConfigDescriptionsTest.java
  itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/internal/VoiceManagerImplTest.java
Labels: test

#2762 Fix dispose is called on handlers for disabled things
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/ThingManagerImplTest.java
Labels: bug

#2778 Flush old JsonStorage to file before recreating a new one
  bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/JsonStorageService.java
Labels: bug

#2781 Prevent errors in log when client closes the HTTP connection
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/GsonMessageBodyWriter.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/JSONResponseExceptionMapper.java
Labels: bug, REST/SSE

#2748 Support multi bundle bindings in i18n-maven-plugin
  tools/i18n-plugin/src/main/java/org/openhab/core/tools/i18n/plugin/BundleInfo.java
  tools/i18n-plugin/src/main/java/org/openhab/core/tools/i18n/plugin/BundleInfoReader.java
  tools/i18n-plugin/src/main/java/org/openhab/core/tools/i18n/plugin/XmlToTranslationsConverter.java
Labels: enhancement, i18n/l10n

#2761 [DialogProcessor] processor aborting before response
  bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java
Labels: bug

#2790 [rest] Improve metadata query parameter description
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/MetadataSelectorMatcher.java
Labels: REST/SSE, documentation

#2788 Fix test failures when building with Java 17
  itests/org.openhab.core.automation.module.script.tests/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/ScriptScopeOSGiTest.java
  pom.xml
Labels: test

#2787 Fix rules stay uninitialized when using Java 17
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/provider/ScriptModuleTypeProvider.java
Labels: bug

#2769 Add a profile for linking trigger channels to String items
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemProfileFactory.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/TriggerEventStringProfile.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/profiles/SystemProfiles.java
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/TriggerEventStringProfileTest.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/profiles/SystemProfileFactoryOSGiTest.java
Labels: enhancement

#2791 [rule] New actions to start/stop dialog processing
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Voice.java
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/engine/action/VoiceActionService.java
Labels: enhancement

#2773 Make ConfigDescription for thing and channels available to ThingHandler
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandler.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/ThingHandlerCallback.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
Labels: enhancement

#2739 [expiry] extend ExpiryManager to allow ignoring state updates
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ExpireManager.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/ExpireManagerTest.java
Labels: enhancement

#2596 [openhab.core] DecimalType-ctor with Number argument
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DecimalType.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/DecimalTypeTest.java
Labels: enhancement

#2772 [rest] Add ability to change loggers and expose package names of addons
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/model/AddonEntryDTO.java
  bundles/org.openhab.core.karaf/pom.xml
  bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonService.java
  bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/LoggerBean.java
  bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/LoggerResource.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/addon/Addon.java
Labels: enhancement

#2785 Fix deadlock when removing ScriptEngine
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java
Labels: bug
