Repository openhab/openhab-core, pull requests merged in 2022-01, with the labels that each got.

#2633 [addonservices] allow offline mode
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java
Labels: enhancement

#2663 Force English locale to parse marketplace UI components timestamp
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityBlockLibaryAddonHandler.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityUIWidgetAddonHandler.java
Labels: bug

#2661 [automation] Align parsing of startlevel config
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
Labels: bug, automation

#2650 [audio] Fix hardcoded value for WAV file
  bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/AudioFormat.java
  bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/FileAudioStream.java
  bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/javasound/AudioPlayer.java
  bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/utils/AudioWaveUtils.java
Labels: bug

#2664 ScriptFileWatcher subdirectory loading upon startup no longer hardcoded
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/ScriptFileWatcher.java
Labels: bug, automation

#2670 [audio] Remove 'clac' noise when playing wave (javasound)
  bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/javasound/AudioPlayer.java
  bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/utils/AudioWaveUtils.java
Labels: bug

#2678 Fix NPE of AddonServices during startup
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java
Labels: bug

#2653 [automation] Log warning for equals condition for DecimalTypes and QuantityTypes
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemStateConditionHandler.java
  bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/handler/ItemStateConditionHandlerTest.java
Labels: enhancement, automation

#2668 [rest] Do not reuse FilterCriteria instance for more than one query
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResource.java
  bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResourceTest.java
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/FilterCriteria.java
Labels: bug, REST/SSE, persistence

#2658 "System reached start level XX" trigger for DSL rules
  bundles/org.openhab.core.model.rule.runtime/src/org/openhab/core/model/rule/runtime/internal/DSLRuleProvider.java
  bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/Rules.xtext
Labels: enhancement, DSL rules

#2538 Include full exception when WatchQueueReader thread dies
  bundles/org.openhab.core/src/main/java/org/openhab/core/service/WatchQueueReader.java
Labels: bug, awaiting feedback

#2682 enable config validation for thing creation and update
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
  bundles/org.openhab.core.thing/src/main/resources/OH-INF/i18n/SystemThingStatusInfos.properties
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/BindingBaseClassesOSGiTest.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingManagerOSGiTest.java
Labels: enhancement

#2706 Script Engines now removed from manager when closed
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java
Labels: bug, automation

#2703 [config] make configuration value parser available for export
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigParser.java
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/Configuration.java
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/ConfigMapper.java
  bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/ConfigParserTest.java
  bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/ConfigurationTest.java
Labels: enhancement

#2709 [REST] Fixed wrong openAPI schema for /inbox
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/discovery/InboxResource.java
Labels: bug, REST/SSE

#2699 [config] Allow String values for other Types
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/TypeIntrospections.java
  bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionValidatorTest.java
Labels: bug

#2714 [voice] Fix getSTT
  bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java
Labels: bug

#2708 [automation] ScriptFileWatcher Initial import now only processes dir
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/ScriptFileWatcher.java
Labels: bug, automation

#2713 [config] improve type validation message
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/MessageKey.java
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/TypeValidator.java
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_ar.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_bg.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_cs.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_de.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_el.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_es.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_fi.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_fr.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_he.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_hu.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_it.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_ja.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_lb.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_nl.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_no.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_pl.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_pt.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_ro.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_ru.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_sv.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_tr.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_uk.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_zh.properties
  bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionValidatorTest.java
Labels: translation

#2718 Fix NPE and exception while parsing config value
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java
Labels: bug

#2693 [voice] Update dialog processing
  bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/VoiceManager.java
  bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java
  bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceConsoleCommandExtension.java
  bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java
  bundles/org.openhab.core.voice/src/main/resources/OH-INF/i18n/voice.properties
  itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/internal/HumanLanguageInterpreterStub.java
  itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/internal/KSServiceStub.java
  itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/internal/STTServiceStub.java
  itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/internal/TTSServiceStub.java
  itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/internal/VoiceManagerImplTest.java
  itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/internal/VoiceStub.java
  itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/voiceconsolecommandextension/InterpretCommandTest.java
  itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/voiceconsolecommandextension/VoicesCommandTest.java
Labels: enhancement
