Repository openhab/openhab-core, pull requests merged in 2022-12, with the labels that each got.

#2887 Add an access-tracking cache to be used in rules
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/CacheScriptExtension.java
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/shared/ValueCache.java
  bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/internal/CacheScriptExtensionTest.java
Labels: enhancement, automation

#3190 [voice] Fix start dialog with non default voice (broken recently)
  bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java
Labels: bug

#3197 Fix DSL action classes regression
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/scoping/ScriptImplicitlyImportedTypes.java
Labels: bug

#3187 DSL support for sharedCache/privateCache
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptExtensionManager.java
  bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java
  bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngineFactory.java
  bundles/org.openhab.core.model.script/bnd.bnd
  bundles/org.openhab.core.model.script/pom.xml
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/jvmmodel/ScriptJvmModelInferrer.xtend
  features/karaf/openhab-core/src/main/feature/feature.xml
  itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun
  itests/org.openhab.core.config.dispatch.tests/itest.bndrun
  itests/org.openhab.core.model.core.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
Labels: enhancement, DSL rules

#3185 ScriptFileWatcher fixes for entire directories
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptFileWatcher.java
  bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptFileWatcherTest.java
Labels: bug

#3204 Fix timer cancellation in automation cache
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/CacheScriptExtension.java
Labels: bug

#2891 Add EventWebSocket
  bom/compile/pom.xml
  bom/openhab-core/pom.xml
  bundles/org.openhab.core.io.websocket/pom.xml
  bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/EventDTO.java
  bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/EventProcessingException.java
  bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/EventWebSocket.java
  bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/EventWebSocketServlet.java
  bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/ItemEventUtility.java
  bundles/org.openhab.core.io.websocket/src/test/java/org/openhab/core/io/websocket/EventWebSocketTest.java
  bundles/org.openhab.core.io.websocket/src/test/java/org/openhab/core/io/websocket/ItemEventUtilityTest.java
  bundles/pom.xml
  features/karaf/openhab-core/src/main/feature/feature.xml
Labels: enhancement

#3202 Fix AVG calculation in GroupFunction
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/ArithmeticGroupFunction.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityTypeArithmeticGroupFunction.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeArithmeticGroupFunctionTest.java
Labels: bug

#3160 [REST] allow running rules with context
  bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/RuleResource.java
Labels: enhancement, REST/SSE

#3145 Add countSince/countBetween to persistence extensions
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
  bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java
Labels: enhancement, persistence

#3208 Fix DataAmount dimension units
  bom/compile/pom.xml
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/Units.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/dimension/DataAmountTest.java
Labels: bug, critical

#3213 Fix default unit for Energy
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java
Labels: bug

#3151 Allow profiles to access the entire context of the link they're applied to
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/ProfileCallbackImpl.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/profiles/ProfileCallback.java
Labels: enhancement

#3216 Fix AbstractScriptFileWatcher missing deletes on Windows
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptFileWatcher.java
Labels: bug, critical

#3139 [audio|voice] Add actions/commands to synthesize melodies and add configurable melody to the dialog processor
  bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/AudioManager.java
  bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioConsoleCommandExtension.java
  bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioManagerImpl.java
  bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/utils/ToneSynthesizer.java
  bundles/org.openhab.core.automation.module.media/src/main/java/org/openhab/core/automation/module/media/internal/MediaActionTypeProvider.java
  bundles/org.openhab.core.automation.module.media/src/main/java/org/openhab/core/automation/module/media/internal/MediaModuleHandlerFactory.java
  bundles/org.openhab.core.automation.module.media/src/main/java/org/openhab/core/automation/module/media/internal/SynthesizeActionHandler.java
  bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/DialogContext.java
  bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java
  bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java
  bundles/org.openhab.core.voice/src/main/resources/OH-INF/config/voice.xml
  bundles/org.openhab.core.voice/src/main/resources/OH-INF/i18n/voice.properties
Labels: enhancement

#3218 GitHub Actions workflow upgrades
  .github/workflows/ci-build.yml
Labels: infrastructure

#3219 Fix BasicAuthentication for websockets
  bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/EventWebSocketServlet.java
Labels: bug

#3225 [rest] Fix missing backward compatibility in rules/runNow
  bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/RuleResource.java
Labels: bug

#3223 Fix wrong websocket topics
  bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/EventWebSocket.java
  bundles/org.openhab.core.io.websocket/src/test/java/org/openhab/core/io/websocket/EventWebSocketTest.java
Labels: bug

#3240 Remove redundant ctor in DecimalType
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DecimalType.java
Labels: API breaking

#2994 Raise minimum JDK version to 17
  .github/workflows/ci-build.yml
  README.md
  bom/compile-model/pom.xml
  bom/compile/pom.xml
  bom/runtime/pom.xml
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/NashornScriptEngineFactory.java
  bundles/pom.xml
  features/karaf/openhab-core/src/main/feature/feature.xml
  features/karaf/openhab-tp/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
  itests/itest-include.bndrun
  itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun
  itests/org.openhab.core.automation.integration.tests/itest.bndrun
  itests/org.openhab.core.automation.module.core.tests/itest.bndrun
  itests/org.openhab.core.automation.module.script.tests/itest.bndrun
  itests/org.openhab.core.automation.module.script.tests/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/ScriptScopeOSGiTest.java
  itests/org.openhab.core.automation.module.script.tests/src/main/resources/OH-INF/automation/jsr223/scopeFailure.js
  itests/org.openhab.core.automation.module.script.tests/src/main/resources/OH-INF/automation/jsr223/scopeWorking.js
  itests/org.openhab.core.automation.module.timer.tests/itest.bndrun
  itests/org.openhab.core.automation.tests/itest.bndrun
  itests/org.openhab.core.binding.xml.tests/itest.bndrun
  itests/org.openhab.core.config.core.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun
  itests/org.openhab.core.config.dispatch.tests/itest.bndrun
  itests/org.openhab.core.config.xml.tests/itest.bndrun
  itests/org.openhab.core.ephemeris.tests/itest.bndrun
  itests/org.openhab.core.io.rest.core.tests/itest.bndrun
  itests/org.openhab.core.model.core.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
  itests/org.openhab.core.storage.json.tests/itest.bndrun
  itests/org.openhab.core.tests/itest.bndrun
  itests/org.openhab.core.thing.tests/itest.bndrun
  itests/org.openhab.core.thing.xml.tests/itest.bndrun
  itests/org.openhab.core.voice.tests/itest.bndrun
  pom.xml
  tools/static-code-analysis/spotbugs/suppressions.xml
Labels: enhancement, API breaking

#3261 Remove wrong DataAmount units
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/Units.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/dimension/DataAmountTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java
Labels: API breaking, UoM

#3280 Only call getVolume when necessary
  bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioManagerImpl.java
  bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java
Labels: enhancement

#3285 Add JavaDoc for the ThingBuilder
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/builder/ThingBuilder.java
Labels: documentation

#3288 Fix Marketplace add-on range pattern matching
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/BundleVersion.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java
Labels: bug

#3287 [core] Add DateTimeType method for returning Instant
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DateTimeType.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/DateTimeTypeTest.java
Labels: enhancement

#3284 Update Jackson to 2.14.1
  bom/runtime/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
  itests/org.openhab.core.io.rest.core.tests/itest.bndrun
  itests/org.openhab.core.model.core.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
Labels: enhancement, dependencies
