Repository openhab/openhab-core, pull requests merged in 2022-06, with the labels that each got.

#2937 Add option for formatting the y-axis labels in charts
  bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java
  bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/WidgetDTO.java
  bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext
  bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/chart/ChartProvider.java
  bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/ChartServlet.java
  bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/defaultchartprovider/DefaultChartProvider.java
Labels: enhancement

#2931 Extend PersistenceExtensions with "between" methods
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
  bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java
Labels: enhancement, persistence

#2996 Fix DateTime trigger syntax to not break the equals function in the execution script
  bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/Rules.xtext
Labels: bug, critical

#2990 Allow DSL scripts for script transformation
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptTransformationService.java
  bundles/org.openhab.core.automation.module.script/src/test/java/org/openhab/core/automation/module/script/ScriptTransformationServiceTest.java
  bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/jvmmodel/ScriptJvmModelInferrer.xtend
Labels: enhancement, DSL

#2986 Fix SSE topic filters
  bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/util/SseUtil.java
  bundles/org.openhab.core.io.rest.sse/src/test/java/org/openhab/core/io/rest/sse/internal/util/SseUtilTest.java
Labels: bug, REST/SSE

#2914 Use ThingStorageEntity instead of ThingImpl/BridgeImpl for storage
  bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/JsonStorageService.java
  bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/migration/BridgeImplTypeMigrator.java
  bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/migration/ThingImplTypeMigrator.java
  bundles/org.openhab.core.storage.json/src/test/java/org/openhab/core/storage/json/internal/ThingStorageEntityMigratorTest.java
  bundles/org.openhab.core.storage.json/src/test/resources/thingMigration-input.json
  bundles/org.openhab.core.storage.json/src/test/resources/thingMigration-result.json
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/ManagedThingProvider.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingStorageEntity.java
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/ManagedThingProviderTest.java
  itests/org.openhab.core.storage.json.tests/itest.bndrun
  itests/org.openhab.core.storage.json.tests/src/main/java/org/openhab/core/storage/json/internal/ThingMigrationOSGiTest.java
  itests/org.openhab.core.storage.json.tests/src/main/resources/org.openhab.core.thing.Thing.json
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/ChangeThingTypeOSGiTest.java
Labels: enhancement

#2940 Refactor thing update handling of ThingManagerImpl
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingRegistryImpl.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingTracker.java
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/ThingManagerImplTest.java
Labels: bug

#2911 Add ability to name timers / scheduled jobs
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/ScriptExecution.java
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/actions/TimerImpl.java
  bundles/org.openhab.core/pom.xml
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/scheduler/DelegatedSchedulerImpl.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/scheduler/SchedulerImpl.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/scheduler/Scheduler.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/internal/scheduler/SchedulerImplTest.java
Labels: enhancement

#3010 Fix config validation for integer values
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/MinMaxValidator.java
  bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionValidatorTest.java
Labels: bug

#3016 Fix ConcurrentModificationException in WatchQueueReader
  bundles/org.openhab.core/src/main/java/org/openhab/core/service/WatchQueueReader.java
Labels: bug

#3015 GitHub Actions workflow improvements
  .github/workflows/ci-build.yml
Labels: infrastructure

#3022 Improve UID error message
  bundles/org.openhab.core/src/main/java/org/openhab/core/common/AbstractUID.java
Labels: enhancement

#3023 Fix symlinks not followed
  bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/FileTransformationConfigurationProvider.java
  bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/internal/CustomIconProvider.java
Labels: bug
