Repository openhab/openhab-core, pull requests merged in 2023-08, with the labels that each got.

#3747 ZipException workarounds
  itests/itest-include.bndrun
  pom.xml
Labels: bug, external bug

#3742 Move factory interface to public package
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/generic/ChannelHandler.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/binding/generic/converter/AbstractTransformingChannelHandler.java
Labels: bug

#3750 Link to Java 17 documentation
  bundles/org.openhab.core/src/main/java/org/openhab/core/common/QueueingThreadPoolExecutor.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/events/TopicEventFilter.java
Labels: documentation

#3748 Fix StackOverflowError in SemanticsMetadataProvider
  bundles/org.openhab.core.semantics/pom.xml
  bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/internal/SemanticsMetadataProvider.java
  bundles/org.openhab.core.semantics/src/test/java/org/openhab/core/semantics/internal/SemanticsMetadataProviderTest.java
Labels: bug

#3754 Fix CME in RuleEngineImpl
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
Labels: bug

#3751 Fix logging in AbstractProvider implementations
  bundles/org.openhab.core.model.persistence/src/org/openhab/core/model/persistence/internal/PersistenceModelManager.java
  bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/GenericItemChannelLinkProvider.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/common/registry/AbstractProvider.java
Labels: enhancement

#3756 Use workaround to fix high CPU usage by LinkedTransferQueue
  bom/compile/pom.xml
  bom/runtime/pom.xml
  bundles/org.openhab.core/src/main/java/org/openhab/core/common/QueueingThreadPoolExecutor.java
  features/karaf/openhab-core/src/main/feature/feature.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
  itests/org.openhab.core.addon.tests/itest.bndrun
  itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun
  itests/org.openhab.core.automation.integration.tests/itest.bndrun
  itests/org.openhab.core.automation.module.core.tests/itest.bndrun
  itests/org.openhab.core.automation.module.script.tests/itest.bndrun
  itests/org.openhab.core.automation.module.timer.tests/itest.bndrun
  itests/org.openhab.core.automation.tests/itest.bndrun
  itests/org.openhab.core.config.core.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun
  itests/org.openhab.core.config.dispatch.tests/itest.bndrun
  itests/org.openhab.core.ephemeris.tests/itest.bndrun
  itests/org.openhab.core.io.net.tests/itest.bndrun
  itests/org.openhab.core.io.rest.core.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
  itests/org.openhab.core.storage.json.tests/itest.bndrun
  itests/org.openhab.core.tests/itest.bndrun
  itests/org.openhab.core.thing.tests/itest.bndrun
  itests/org.openhab.core.voice.tests/itest.bndrun
Labels: bug

#3758 Bump UoM libraries to 2.2
  bom/compile/pom.xml
  bom/runtime/pom.xml
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/UnitsTest.java
  features/karaf/openhab-tp/src/main/feature/feature.xml
  itests/org.openhab.core.addon.tests/itest.bndrun
  itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun
  itests/org.openhab.core.automation.integration.tests/itest.bndrun
  itests/org.openhab.core.automation.module.core.tests/itest.bndrun
  itests/org.openhab.core.automation.module.script.tests/itest.bndrun
  itests/org.openhab.core.automation.module.timer.tests/itest.bndrun
  itests/org.openhab.core.automation.tests/itest.bndrun
  itests/org.openhab.core.config.core.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun
  itests/org.openhab.core.config.dispatch.tests/itest.bndrun
  itests/org.openhab.core.ephemeris.tests/itest.bndrun
  itests/org.openhab.core.io.net.tests/itest.bndrun
  itests/org.openhab.core.io.rest.core.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
  itests/org.openhab.core.storage.json.tests/itest.bndrun
  itests/org.openhab.core.tests/itest.bndrun
  itests/org.openhab.core.thing.tests/itest.bndrun
  itests/org.openhab.core.voice.tests/itest.bndrun
  tools/upgradetool/pom.xml
Labels: UoM, dependencies

#3760 Improve AutomationIntegrationJsonTest
  itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationJsonTest.java
Labels: test

#3765 Upgrade org.bouncycastle:bcpkix-jdk15on
  bundles/org.openhab.core.io.jetty.certificate/pom.xml
Labels: dependencies, security

#3768 Update Jackson to 2.15.2
  bom/runtime/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
  itests/org.openhab.core.io.rest.core.tests/itest.bndrun
Labels: dependencies, security

#3770 Update CXF to 3.6.1
  bom/runtime/pom.xml
  bom/test/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
  itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun
  itests/org.openhab.core.automation.integration.tests/itest.bndrun
  itests/org.openhab.core.automation.module.core.tests/itest.bndrun
  itests/org.openhab.core.automation.module.script.tests/itest.bndrun
  itests/org.openhab.core.automation.module.timer.tests/itest.bndrun
  itests/org.openhab.core.automation.tests/itest.bndrun
  itests/org.openhab.core.config.core.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun
  itests/org.openhab.core.config.dispatch.tests/itest.bndrun
  itests/org.openhab.core.ephemeris.tests/itest.bndrun
  itests/org.openhab.core.io.net.tests/itest.bndrun
  itests/org.openhab.core.io.rest.core.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
  itests/org.openhab.core.storage.json.tests/itest.bndrun
  itests/org.openhab.core.tests/itest.bndrun
Labels: dependencies, security

#3772 Update json-path to 2.8.0
  bom/test/pom.xml
  itests/org.openhab.core.io.rest.core.tests/itest.bndrun
Labels: test, dependencies, security

#3769 Fix sitemap visibility rule with blanks
  bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
Labels: bug

#3780 Fix compilerArguments deprecation warnings
  pom.xml
Labels: infrastructure

#3781 Fix SAT and null analysis issues
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/profile/ScriptProfileFactory.java
  bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/RuleResource.java
  bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/AuthFilter.java
  bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/CommunicationManagerConversionTest.java
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/binding/AbstractStorageBasedTypeProviderTest.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ItemStateConverterImpl.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/NumberItem.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/internal/i18n/I18nProviderImplTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java
  itests/org.openhab.core.automation.module.core.tests/src/main/java/org/openhab/core/automation/internal/module/RunRuleModuleTest.java
  itests/org.openhab.core.automation.module.core.tests/src/main/java/org/openhab/core/automation/internal/module/RuntimeRuleTest.java
  itests/org.openhab.core.automation.module.timer.tests/src/main/java/org/openhab/core/automation/module/timer/internal/BasicConditionHandlerTest.java
  itests/org.openhab.core.automation.module.timer.tests/src/main/java/org/openhab/core/automation/module/timer/internal/DayOfWeekConditionHandlerTest.java
  itests/org.openhab.core.automation.module.timer.tests/src/main/java/org/openhab/core/automation/module/timer/internal/RuntimeRuleTest.java
  itests/org.openhab.core.automation.tests/src/main/java/org/openhab/core/automation/event/RuleEventTest.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/AbstractStorageBasedTypeProviderOSGiTest.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/CommunicationManagerOSGiTest.java
Labels: bug

#3782 Fix linuxsysfs itest failing when serial device is connected
  bundles/org.openhab.core.config.discovery.usbserial.linuxsysfs/src/main/java/org/openhab/core/config/discovery/usbserial/linuxsysfs/internal/SysfsUsbSerialScanner.java
Labels: test

#3779 Fix GenericThingProvider
  bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/GenericThingProvider.xtend
Labels: bug

#3789 Update Swagger to 2.2.15
  bom/compile/pom.xml
  bom/runtime/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
Labels: dependencies

#3790 Update directory-watcher to 0.18.0
  bom/compile/pom.xml
  bom/runtime/pom.xml
  features/karaf/openhab-core/src/main/feature/feature.xml
  itests/org.openhab.core.addon.tests/itest.bndrun
  itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun
  itests/org.openhab.core.automation.integration.tests/itest.bndrun
  itests/org.openhab.core.automation.module.core.tests/itest.bndrun
  itests/org.openhab.core.automation.module.script.tests/itest.bndrun
  itests/org.openhab.core.automation.module.timer.tests/itest.bndrun
  itests/org.openhab.core.automation.tests/itest.bndrun
  itests/org.openhab.core.config.core.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun
  itests/org.openhab.core.config.dispatch.tests/itest.bndrun
  itests/org.openhab.core.ephemeris.tests/itest.bndrun
  itests/org.openhab.core.io.net.tests/itest.bndrun
  itests/org.openhab.core.io.rest.core.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
  itests/org.openhab.core.storage.json.tests/itest.bndrun
  itests/org.openhab.core.tests/itest.bndrun
  itests/org.openhab.core.thing.tests/itest.bndrun
  itests/org.openhab.core.voice.tests/itest.bndrun
Labels: dependencies
