Repository openhab/openhab-core, pull requests merged in 2023-04, with the labels that each got.

#3513 Fix resource leak in SysfsUsbSerialScanner
  bundles/org.openhab.core.config.discovery.usbserial.linuxsysfs/src/main/java/org/openhab/core/config/discovery/usbserial/linuxsysfs/internal/SysfsUsbSerialScanner.java
Labels: bug, critical

#3510 Fix AbstractDependencyTracker
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptDependencyTracker.java
  bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptDependencyTrackerTest.java
Labels: bug

#3518 Fix WatchService tests
  bundles/org.openhab.core/src/test/java/org/openhab/core/internal/service/WatchServiceImplTest.java
Labels: test

#3528 Fix IllegalStateException in CommunityKarafAddonHandler
  bundles/org.openhab.core.addon.marketplace.karaf/src/main/java/org/openhab/core/addon/marketplace/karaf/internal/community/CommunityKarafAddonHandler.java
Labels: bug, critical, regression

#3529 Fix wrong event subscription in `CommunicationManager`
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/CommunicationManager.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/GroupItem.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemEventFactory.java
Labels: bug, regression

#3524 Prevent unnecessary MODIFY events in WatchServiceImpl
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/service/WatchServiceImpl.java
Labels: bug

#3439 [persistence] fix time weighting in averageSince and averageBetween
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
  bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java
  bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/TestCachedValuesPersistenceService.java
Labels: enhancement

#3535 Improve log messages in ItemStateConditionHandler
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemStateConditionHandler.java
Labels: enhancement

#3539 Extend item syntax for category/icon
  bundles/org.openhab.core.model.item/src/org/openhab/core/model/Items.xtext
Labels: enhancement

#3378 Extend sitemap syntax for icon
  bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext
Labels: enhancement

#3431 Add Input widget to main UI sitemap configuration and REST API
  bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java
  bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/WidgetDTO.java
  bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
Labels: enhancement

#3519 Add dynamic creation of semantic tags
  bundles/org.openhab.core.semantics/model/generateTagClasses.groovy
  bundles/org.openhab.core.semantics/pom.xml
  bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/SemanticTags.java
  bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/model/equipment/Equipments.java
  bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/model/location/Locations.java
  bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/model/point/Points.java
  bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/model/property/Properties.java
  bundles/org.openhab.core.semantics/src/test/java/org/openhab/core/semantics/SemanticTagsTest.java
  features/karaf/openhab-core/src/main/feature/feature.xml
Labels: enhancement

#3549 Fix IndexOutOfBoundsException in ScriptEngineFactoryHelper
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineFactoryHelper.java
Labels: bug

#3537 [oauth] Add support for custom deserialization of AccessTokenResponse
  bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthClientServiceImpl.java
  bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthConnector.java
  bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/PersistedParams.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/auth/client/oauth2/OAuthClientService.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/auth/client/oauth2/OAuthFactory.java
Labels: enhancement, API breaking

#3532 Fix hidden files showing up in TransformationRegistry
  bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/FileTransformationProvider.java
Labels: bug

#3526 Fix thing reloading from things file
  bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/GenericThingProvider.xtend
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/Channel.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/util/ThingHelper.java
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/util/ThingHelperTest.java
Labels: bug

#3533 Fix wrong event subscription in GroupStateTrigger and ItemStateTrigger
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GroupStateTriggerHandler.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemStateTriggerHandler.java
Labels: bug

#3553 Add methods to get Semantic tag synonyms and description
  bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/SemanticTags.java
  bundles/org.openhab.core.semantics/src/test/java/org/openhab/core/semantics/SemanticTagsTest.java
Labels: enhancement

#3548 Icon server: remove old style request with the state in the URL
  bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/internal/IconServlet.java
  bundles/org.openhab.core.ui.icon/src/test/java/org/openhab/core/ui/icon/AbstractResourceIconProviderTest.java
  bundles/org.openhab.core.ui.icon/src/test/java/org/openhab/core/ui/icon/internal/IconServletTest.java
Labels: enhancement

#3542 [ColorUtil] Add fine precision methods
  bundles/org.openhab.core/src/main/java/org/openhab/core/util/ColorUtil.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/HSBTypeTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/util/ColorUtilTest.java
Labels: enhancement

#3575 Consider auto-update policy from channel types
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/AutoUpdatePolicy.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/ThingChannelsTest.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/AutoUpdateManagerTest.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/CommunicationManagerOSGiTest.java
Labels: bug

#3550 Remove GenericScriptEngineFactory
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/GenericScriptEngineFactory.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineFactoryHelper.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java
Labels: enhancement
