Repository openhab/openhab-core, pull requests merged in 2023-05, with the labels that each got.

#3586 Reduce SAT warnings
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/profile/ProfileTypeResource.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/tag/TagResource.java
  bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/util/SseUtil.java
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/AutoUpdateManager.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/events/OSGiEventPublisher.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/service/WatchServiceImpl.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/HSBTypeTest.java
Labels: enhancement

#3587 Change default imperial unit for length to inch
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java
Labels: bug

#3573 [ephemeris] Add support for overriding holiday definitions
  bundles/org.openhab.core.ephemeris/src/main/java/org/openhab/core/ephemeris/internal/EphemerisManagerImpl.java
  bundles/org.openhab.core.ephemeris/src/main/resources/jollyday/holidays/Holidays_dk.xml
  itests/org.openhab.core.ephemeris.tests/src/main/java/org/openhab/core/ephemeris/internal/EphemerisManagerImplOSGiTest.java
Labels: enhancement

#3593 Improve message when rule action fails
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
Labels: enhancement

#3592 Fix non-unique module handler identifiers
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/handler/BaseModuleHandlerFactory.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/composite/CompositeModuleHandlerFactory.java
Labels: bug

#3576 Improve thing updates
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_cs.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_de.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_he.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_hu.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_it.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_no.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_pl.properties
  bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_sl.properties
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingFactoryHelper.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/update/ThingUpdateInstructionReader.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/update/ThingUpdateInstructionReaderImpl.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/update/UpdateChannelInstructionImpl.java
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/ThingManagerImplTest.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/update/ThingUpdateOSGiTest.java
Labels: bug

#3407 Add an AbstractStorageBasedTypeProvider
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/AbstractStorageBasedTypeProvider.java
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/binding/AbstractStorageBasedTypeProviderTest.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/AbstractStorageBasedTypeProviderOSGiTest.java
Labels: enhancement

#3596 Fix build (AbstractStorageBasedTypeProviderTest)
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/binding/AbstractStorageBasedTypeProviderTest.java
Labels: bug, regression

#3598 Fix storing of StateDescriptionFragment in AbstractStorageBasedTypeProvider
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/AbstractStorageBasedTypeProvider.java
Labels: bug

#3481 [uom] Add `unit` metadata for NumberItem
  bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/handler/ItemStateConditionHandlerTest.java
  bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/item/EnrichedItemDTOMapperTest.java
  bundles/org.openhab.core.model.script/src.moved/test/java/org/openhab/core/model/script/actions/SemanticsTest.java
  bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java
  bundles/org.openhab.core.semantics/src/test/java/org/openhab/core/semantics/SemanticTagsTest.java
  bundles/org.openhab.core.semantics/src/test/java/org/openhab/core/semantics/SemanticsPredicatesTest.java
  bundles/org.openhab.core.semantics/src/test/java/org/openhab/core/semantics/internal/SemanticsServiceImplTest.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/CommunicationManager.java
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/CommunicationManagerConversionTest.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/i18n/UnitProvider.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ItemRegistryImpl.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/GenericItem.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/GroupItem.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/MetadataAwareItem.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/CoreItemFactory.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/NumberItem.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/types/util/UnitUtils.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/internal/i18n/TestUnitProvider.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/ExpireManagerTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/items/GenericItemTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/items/GroupItemTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/CoreItemFactoryTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/items/NumberItemTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeArithmeticGroupFunctionTest.java
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/src/main/java/org/openhab/core/model/script/engine/ScriptEngineOSGiTest.java
  itests/org.openhab.core.tests/src/main/java/org/openhab/core/items/GroupItemOSGiTest.java
  itests/org.openhab.core.tests/src/main/java/org/openhab/core/items/ItemRegistryImplTest.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/CommunicationManagerOSGiTest.java
  tools/upgradetool/src/main/java/org/openhab/core/tools/internal/Upgrader.java
Labels: enhancement, API breaking, UoM

#3607 Fix UpgradeTool and enable default=all policy
  tools/upgradetool/src/main/java/org/openhab/core/tools/UpgradeTool.java
  tools/upgradetool/src/main/java/org/openhab/core/tools/internal/Upgrader.java
Labels: bug

#3609 Reduce loglevel in UnitUtils
  bundles/org.openhab.core/src/main/java/org/openhab/core/types/util/UnitUtils.java
Labels: bug

#3572 Fix marketplace add-on services fail after upgrade
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonService.java
Labels: bug

#3614 Fix UpgradeTool execution log
  tools/upgradetool/src/main/java/org/openhab/core/tools/internal/Upgrader.java
Labels: bug, regression

#3621 Fix Upgradetool does not remember last executed step
  tools/upgradetool/src/main/java/org/openhab/core/tools/internal/Upgrader.java
Labels: bug, regression

#3608 Add dimension RadiationSpecificActivity
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/dimension/RadiationSpecificActivity.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/Units.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/UnitsTest.java
Labels: bug

#3627 Fix exception in TransformationHelper
  bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/TransformationHelper.java
Labels: bug

#3626 Move LSP service from misc to system
  bundles/org.openhab.core.model.lsp/src/main/java/org/openhab/core/model/lsp/internal/ModelServer.java
  bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/config/lsp.xml
  bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp.properties
  bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_cs.properties
  bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_da.properties
  bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_de.properties
  bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_el.properties
  bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_fi.properties
  bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_fr.properties
  bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_he.properties
  bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_hu.properties
  bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_it.properties
  bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_nl.properties
  bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_no.properties
  bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_pl.properties
  bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_pt.properties
  bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_ru.properties
  bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_sl.properties
  bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_sv.properties
  bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_uk.properties
  bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_zh.properties
Labels: enhancement

#3625 Move RuleHLI service from voice to system
  bundles/org.openhab.core.model.script/resources/OH-INF/config/hli.xml
  bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli.properties
  bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_cs.properties
  bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_da.properties
  bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_de.properties
  bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_el.properties
  bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_fi.properties
  bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_fr.properties
  bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_he.properties
  bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_hu.properties
  bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_it.properties
  bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_nl.properties
  bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_no.properties
  bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_pl.properties
  bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_pt.properties
  bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_ru.properties
  bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_sl.properties
  bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_sv.properties
  bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_uk.properties
  bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_zh.properties
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/RuleHumanLanguageInterpreter.java
Labels: enhancement

#3630 Fix NPE in UpgradeTool when no pattern present
  tools/upgradetool/src/main/java/org/openhab/core/tools/internal/Upgrader.java
Labels: bug

#3628 Fix event ordering for item events
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ItemRegistryImpl.java
Labels: bug

#3634 Remove package support from FeatureInstaller
  bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java
Labels: enhancement

#3633 Fix NPE in WatchServiceImpl
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/service/WatchServiceImpl.java
Labels: bug

#3611 [rest] Add endpoint for UoM information
  bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/resources/SystemInfoResource.java
  bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/resources/beans/UoMInfoBean.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/i18n/UnitProvider.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/internal/i18n/TestUnitProvider.java
Labels: enhancement, REST/SSE

#3536 Add group name to GroupStateTriggerHandler
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GroupCommandTriggerHandler.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GroupStateTriggerHandler.java
  bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/ItemTriggers.json
  bundles/org.openhab.core.automation/src/main/resources/OH-INF/i18n/automation.properties
  bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/jvmmodel/ScriptJvmModelInferrer.xtend
Labels: enhancement

#3275 Add a ScriptEngineFactory bundle tracker
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineFactoryBundleTracker.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/service/StartLevelService.java
Labels: enhancement

#3278 Trigger immediately when start level already reached
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/factory/CoreModuleHandlerFactory.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/SystemTriggerHandler.java
  bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/handler/SystemTriggerHandlerTest.java
  bundles/org.openhab.core.test/src/main/java/org/openhab/core/test/java/JavaOSGiTest.java
  itests/org.openhab.core.automation.integration.tests/itest.bndrun
  itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationJsonTest.java
  itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationTest.java
  itests/org.openhab.core.automation.module.core.tests/itest.bndrun
  itests/org.openhab.core.automation.module.core.tests/src/main/java/org/openhab/core/automation/internal/module/RunRuleModuleTest.java
  itests/org.openhab.core.automation.module.core.tests/src/main/java/org/openhab/core/automation/internal/module/RuntimeRuleTest.java
  itests/org.openhab.core.automation.module.timer.tests/itest.bndrun
  itests/org.openhab.core.automation.module.timer.tests/src/main/java/org/openhab/core/automation/module/timer/internal/BasicConditionHandlerTest.java
  itests/org.openhab.core.automation.module.timer.tests/src/main/java/org/openhab/core/automation/module/timer/internal/DayOfWeekConditionHandlerTest.java
  itests/org.openhab.core.automation.module.timer.tests/src/main/java/org/openhab/core/automation/module/timer/internal/RuntimeRuleTest.java
  itests/org.openhab.core.automation.tests/itest.bndrun
  itests/org.openhab.core.automation.tests/src/main/java/org/openhab/core/automation/event/RuleEventTest.java
Labels: bug

#2965 Add event information in rules for time, manual and RunRuleAction trigger
  bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/RuleResource.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/events/AutomationEventFactory.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/events/ExecutionEvent.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/events/TimerEvent.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/DateTimeTriggerHandler.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GenericCronTriggerHandler.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/RunRuleActionHandler.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/TimeOfDayTriggerHandler.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/events/AbstractEventFactory.java
Labels: enhancement
