Repository openhab/openhab-core, pull requests merged in 2023-12, with the labels that each got.

#3889 Add time-series support for websockets
  bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/event/EventWebSocket.java
  bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/event/ItemEventUtility.java
  bundles/org.openhab.core.io.websocket/src/test/java/org/openhab/core/io/websocket/ItemEventUtilityTest.java
Labels: enhancement

#3659 Add a YAML file provider for semantic tags
  bom/openhab-core/pom.xml
  bundles/org.openhab.core.model.yaml/.classpath
  bundles/org.openhab.core.model.yaml/.project
  bundles/org.openhab.core.model.yaml/NOTICE
  bundles/org.openhab.core.model.yaml/pom.xml
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/AbstractYamlFile.java
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/YamlElement.java
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/YamlFile.java
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/YamlModelListener.java
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/YamlParseException.java
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepository.java
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/semantics/YamlSemanticTag.java
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/semantics/YamlSemanticTagProvider.java
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/semantics/YamlSemanticTags.java
  bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/internal/SemanticsMetadataProvider.java
  bundles/pom.xml
  features/karaf/openhab-core/src/main/feature/feature.xml
Labels: enhancement

#3503 [UoM] Add currency handling
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/CurrencyServiceConfigOptionProvider.java
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/i18n/I18nConfigOptionsProvider.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/library/unit/CurrencyConverter.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/library/unit/CurrencyService.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/library/unit/FixedCurrencyProvider.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/library/unit/LocaleBasedCurrencyProvider.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/library/unit/UnitInitializer.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/dimension/Currency.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/dimension/EnergyPrice.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/CurrencyProvider.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/CurrencyUnit.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/CurrencyUnits.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/types/util/UnitUtils.java
  bundles/org.openhab.core/src/main/resources/OH-INF/config/units.xml
  bundles/org.openhab.core/src/test/java/org/openhab/core/internal/i18n/I18nProviderImplTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/CurrencyUnitTest.java
Labels: enhancement

#3931 Don't log errors on NotFoundExceptions in Jetty
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/JSONResponseExceptionMapper.java
Labels: bug

#3935 Upgrade logback-classic to 1.3.14
  bundles/org.openhab.core.test/pom.xml
  bundles/org.openhab.core/pom.xml
  itests/org.openhab.core.addon.tests/itest.bndrun
  itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun
  itests/org.openhab.core.automation.integration.tests/itest.bndrun
  itests/org.openhab.core.automation.module.core.tests/itest.bndrun
  itests/org.openhab.core.automation.module.script.tests/itest.bndrun
  itests/org.openhab.core.automation.module.timer.tests/itest.bndrun
  itests/org.openhab.core.automation.tests/itest.bndrun
  itests/org.openhab.core.config.core.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun
  itests/org.openhab.core.config.dispatch.tests/itest.bndrun
  itests/org.openhab.core.ephemeris.tests/itest.bndrun
  itests/org.openhab.core.io.net.tests/itest.bndrun
  itests/org.openhab.core.io.rest.core.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
  itests/org.openhab.core.storage.json.tests/itest.bndrun
  itests/org.openhab.core.tests/itest.bndrun
  itests/org.openhab.core.thing.tests/itest.bndrun
  itests/org.openhab.core.voice.tests/itest.bndrun
  itests/pom.xml
Labels: test, dependencies, security

#3941 Provide I18N properties for Unit Settings
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/i18n.properties
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/network.properties
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/units.properties
Labels: i18n/l10n

#3949 Catch ISE if config admin is no longer available
  bundles/org.openhab.core.config.discovery.addon/src/main/java/org/openhab/core/config/discovery/addon/AddonSuggestionService.java
Labels: bug

#3951 Delay the IP scan to make sure that no further candidates are added
  bundles/org.openhab.core.config.discovery.addon.ip/src/main/java/org/openhab/core/config/discovery/addon/ip/IpAddonFinder.java
Labels: bug

#3964 Fix month, week, day not supported
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/Units.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/UnitsTest.java
Labels: bug

#3961 Fix duplicate UIDs in remote add-on services
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonService.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java
  bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonServiceTest.java
Labels: bug

#3968 Remove unnecessary parenthesis from lambdas
  bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioManagerImpl.java
  bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/ConfigurableServiceUtilTest.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/service/ConfigurableServiceResource.java
  bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java
  bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/AbstractRuleBasedInterpreter.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/common/ThreadPoolManager.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/scheduler/CronAdjuster.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/cache/lru/LRUMediaCacheTest.java
Labels: enhancement

#3970 [rest] Add `no-cache` directive to cached REST responses
  bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/RuleResource.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/tag/TagResource.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java
  bundles/org.openhab.core.io.rest.ui/src/main/java/org/openhab/core/io/rest/ui/internal/UIResource.java
  bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/resources/SystemInfoResource.java
Labels: bug

#3922 Add-on suggestion finder for USB devices
  bom/openhab-core/pom.xml
  bundles/org.openhab.core.config.discovery.addon.process/src/main/java/org/openhab/core/config/discovery/addon/process/ProcessAddonFinder.java
  bundles/org.openhab.core.config.discovery.addon.upnp/src/main/java/org/openhab/core/config/discovery/addon/upnp/UpnpAddonFinder.java
  bundles/org.openhab.core.config.discovery.addon.usb/.classpath
  bundles/org.openhab.core.config.discovery.addon.usb/.project
  bundles/org.openhab.core.config.discovery.addon.usb/NOTICE
  bundles/org.openhab.core.config.discovery.addon.usb/pom.xml
  bundles/org.openhab.core.config.discovery.addon.usb/src/main/java/org/openhab/core/config/discovery/addon/usb/UsbAddonFinder.java
  bundles/org.openhab.core.config.discovery.addon.usb/src/test/java/org/openhab/core/config/discovery/addon/usb/UsbAddonFinderTests.java
  bundles/org.openhab.core.config.discovery.addon/src/main/java/org/openhab/core/config/discovery/addon/AddonFinderConstants.java
  bundles/org.openhab.core.config.discovery.usbserial.ser2net/src/main/java/org/openhab/core/config/discovery/usbserial/ser2net/internal/Ser2NetUsbSerialDiscovery.java
  bundles/org.openhab.core.config.discovery.usbserial.ser2net/src/test/java/org/openhab/core/config/discovery/usbserial/ser2net/internal/Ser2NetUsbSerialDiscoveryTest.java
  bundles/org.openhab.core.config.discovery.usbserial/src/main/java/org/openhab/core/config/discovery/usbserial/UsbSerialDeviceInformation.java
  bundles/org.openhab.core/src/main/resources/OH-INF/config/addons.xml
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/addons.properties
  bundles/pom.xml
  features/karaf/openhab-core/src/main/feature/feature.xml
Labels: enhancement

#3966 Fix NPE in GroupStateTriggerHandler and GroupCommandTriggerHandler
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GroupCommandTriggerHandler.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GroupStateTriggerHandler.java
  bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/handler/GroupCommandTriggerHandlerTest.java
  bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/handler/GroupStateTriggerHandlerTest.java
Labels: bug

#3978 Consider network settings to avoid creating unexpected JmDNS instances
  bundles/org.openhab.core.io.transport.mdns/src/main/java/org/openhab/core/io/transport/mdns/internal/MDNSClientImpl.java
Labels: bug

#3980 [sitemap] Fix parsing of button (buttongrid element built with MainUI)
  bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
Labels: bug

#3989 Respond with 404 if add-on is missing in add-on service
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/addons/AddonResource.java
Labels: bug

#3981 Add network-interface context
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/net/NetworkConfigOptionProvider.java
Labels: enhancement
