Repository openhab/openhab-core, pull requests merged in 2023-01, with the labels that each got.

#2810 [rest] Allow invoking ThingActions via API
  bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/ThingActionsResource.java
Labels: enhancement, REST/SSE

#3298 Add method to get namespaces to MetadataRegistry and ItemResource
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/MetadataRegistryImpl.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/MetadataRegistry.java
Labels: enhancement, REST/SSE

#3277 Fix DateTimeTrigger not triggering on restored state
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/DateTimeTriggerHandler.java
Labels: bug

#3270 Log the version/build on startup
  bundles/org.openhab.core/src/main/java/org/openhab/core/Activator.java
Labels: enhancement

#3273 Ensure metadata available at startlevel 20
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/MetadataRegistryImpl.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/MetadataCommandDescriptionProviderTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/MetadataRegistryImplTest.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/MetadataStateDescriptionFragmentProviderTest.java
Labels: bug

#3255 Refactor AbstractScriptFileWatcher
  bundles/org.openhab.core.automation.module.script.rulesupport/pom.xml
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/BidiSetBag.java
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/DefaultScriptFileWatcher.java
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileReference.java
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptDependencyTracker.java
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptFileWatcher.java
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/ScriptFileReference.java
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/ScriptFileWatcher.java
  bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptFileWatcherTest.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptEngineManager.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java
Labels: bug, API breaking

#3320 Fix addon.xsd
  bundles/org.openhab.core.addon.xml/addon-1.0.0.xsd
Labels: bug

#3322 Fix logger package addition in KarafAddonService
  bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonService.java
Labels: bug, regression

#3241 Improve channel handling in ThingImpl
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/ManagedThingProvider.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/BridgeImpl.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingImpl.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/util/ThingHelper.java
  itests/org.openhab.core.storage.json.tests/src/main/java/org/openhab/core/storage/json/internal/ThingMigrationOSGiTest.java
Labels: enhancement

#3293 Fixes and enhancements for add-on services
  bundles/org.openhab.core.addon.marketplace.karaf/src/main/java/org/openhab/core/addon/marketplace/karaf/internal/community/CommunityKarafAddonHandler.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonService.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityBlockLibaryAddonHandler.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityBundleAddonHandler.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityRuleTemplateAddonHandler.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityUIWidgetAddonHandler.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/model/AddonEntryDTO.java
  bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonServiceTest.java
  bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/marketplace/test/TestAddonHandler.java
  bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/marketplace/test/TestAddonService.java
  bundles/org.openhab.core.addon.sample/src/main/java/org/openhab/core/addon/sample/internal/SampleAddonService.java
  bundles/org.openhab.core.addon.xml/src/main/java/org/openhab/core/addon/xml/internal/AddonInfoConverter.java
  bundles/org.openhab.core.addon.xml/src/main/java/org/openhab/core/addon/xml/internal/AddonInfoReader.java
  bundles/org.openhab.core.addon.xml/src/main/java/org/openhab/core/addon/xml/internal/AddonInfoXmlProvider.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/addons/AddonResource.java
  bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonService.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/addon/Addon.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/addon/AddonI18nLocalizationService.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/addon/AddonInfo.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/addon/JarFileAddonService.java
Labels: bug, enhancement, critical

#3337 [REST] Consider language when requesting thing actions
  bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/ThingActionsResource.java
Labels: enhancement, i18n/l10n

#3341 Consider language in KarafAddonService when creating Addon
  bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonService.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/addon/AddonI18nUtil.java
  itests/org.openhab.core.addon.xml.tests/src/main/resources/test-bundle-pool/acmeweather.bundle/OH-INF/i18n/acmeweather_de.properties
  itests/org.openhab.core.addon.xml.tests/src/main/resources/test-bundle-pool/acmeweather.bundle/OH-INF/i18n/acmeweather_nl.properties
Labels: bug, regression

#3343 Build default doc link for misc and ui bindings
  bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonService.java
Labels: bug, regression

#3339 Properly handle failure when parsing marketplace add-ons
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java
Labels: bug

#3334 Fix parsing of YAML default value for community marketplace UI Widgets
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityUIWidgetAddonHandler.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/SerializedNameAnnotationIntrospector.java
Labels: bug
