Repository openhab/openhab-core, pull requests merged in 2024-02, with the labels that each got.

#4024 Improve YAML model repository
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/AbstractYamlFile.java
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/YamlElement.java
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/YamlElementName.java
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/YamlFile.java
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/YamlModelListener.java
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/YamlModelRepository.java
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/YamlParseException.java
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepository.java
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImpl.java
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelWrapper.java
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/semantics/YamlSemanticTagDTO.java
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/semantics/YamlSemanticTagProvider.java
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/semantics/YamlSemanticTags.java
  bundles/org.openhab.core.model.yaml/src/test/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImplTest.java
  bundles/org.openhab.core.model.yaml/src/test/java/org/openhab/core/model/yaml/test/FirstTypeDTO.java
  bundles/org.openhab.core.model.yaml/src/test/java/org/openhab/core/model/yaml/test/SecondTypeDTO.java
  bundles/org.openhab.core.model.yaml/src/test/resources/addToModelExpectedContent.yaml
  bundles/org.openhab.core.model.yaml/src/test/resources/modelFileAddedOrRemoved.yaml
  bundles/org.openhab.core.model.yaml/src/test/resources/modelFileUpdatePost.yaml
  bundles/org.openhab.core.model.yaml/src/test/resources/modelFileUpdatePre.yaml
  bundles/org.openhab.core.model.yaml/src/test/resources/modifyModelInitialContent.yaml
  bundles/org.openhab.core.model.yaml/src/test/resources/removeFromModelExpectedContent.yaml
  bundles/org.openhab.core.model.yaml/src/test/resources/updateInModelExpectedContent.yaml
  tools/static-code-analysis/checkstyle/suppressions.xml
Labels: enhancement

#4075 Fix reloading channel config changes in .items file
  bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/GenericItemChannelLinkProvider.java
Labels: bug

#4069 [UoM] Add dimension for emission intensity
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/dimension/EmissionIntensity.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/Units.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/UnitsTest.java
Labels: enhancement

#4058 Script profile: Separate toHandlerScript for commands and states
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/profile/ScriptProfile.java
  bundles/org.openhab.core.automation.module.script/src/main/resources/OH-INF/config/script-profile.xml
  bundles/org.openhab.core.automation.module.script/src/main/resources/OH-INF/i18n/scriptprofile.properties
  bundles/org.openhab.core.automation.module.script/src/test/java/org/openhab/core/automation/module/script/profile/ScriptProfileTest.java
Labels: enhancement

#4086 Fix CME in ReadyService
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/service/ReadyServiceImpl.java
Labels: bug

#4088 Fix the recursive group membership check
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/item/EnrichedItemDTOMapper.java
  bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/item/EnrichedItemDTOMapperTest.java
  bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/internal/SemanticsMetadataProvider.java
  bundles/org.openhab.core.semantics/src/test/java/org/openhab/core/semantics/internal/SemanticsMetadataProviderTest.java
Labels: bug

#4084 [sitemap] Add releaseOnly parameter to Slider sitemap element
  bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java
  bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/WidgetDTO.java
  bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext
  bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
  bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java
  bundles/org.openhab.core.ui/src/test/java/org/openhab/core/ui/internal/items/ItemUIRegistryImplTest.java
Labels: enhancement

#4089 [persistence] Fix forecast for externally changed data
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResource.java
  bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResourceTest.java
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/PersistenceManager.java
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceManagerImpl.java
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/registry/PersistenceServiceConfigurationRegistry.java
  bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/internal/PersistenceManagerTest.java
Labels: bug

#4091 Fix itests not running
  itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun
  itests/org.openhab.core.automation.integration.tests/itest.bndrun
  itests/org.openhab.core.automation.module.core.tests/itest.bndrun
  itests/org.openhab.core.automation.module.script.tests/itest.bndrun
  itests/org.openhab.core.automation.module.timer.tests/itest.bndrun
  itests/org.openhab.core.automation.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
  itests/org.openhab.core.storage.json.tests/itest.bndrun
  itests/org.openhab.core.thing.tests/itest.bndrun
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/AutoUpdateManagerTest.java
  itests/org.openhab.core.voice.tests/itest.bndrun
Labels: test

#3943 Minor extension to generic ip discovery
  bundles/org.openhab.core.config.discovery.addon.ip/src/main/java/org/openhab/core/config/discovery/addon/ip/IpAddonFinder.java
Labels: enhancement

#4098 Upgrade jUPnP to 3.0.0
  bom/compile/pom.xml
  bom/openhab-core/pom.xml
  bom/runtime/pom.xml
  bundles/org.openhab.core.config.jupnp/.classpath
  bundles/org.openhab.core.config.jupnp/.project
  bundles/org.openhab.core.config.jupnp/NOTICE
  bundles/org.openhab.core.config.jupnp/pom.xml
  bundles/org.openhab.core.config.jupnp/src/main/java/org/openhab/core/config/jupnp/internal/OHUpnpServiceConfiguration.java
  bundles/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
Labels: dependencies
