Repository openhab/openhab-core, pull requests merged in 2024-10, with the labels that each got.

#4397 Ensure timeseries entries have unique timestamps
  bundles/org.openhab.core.automation.module.script/src/test/java/org/openhab/core/automation/module/script/profile/ScriptProfileTest.java
Labels: regression

#4403 Upgrade Jollyday to 0.32.0
  bom/compile/pom.xml
  bom/runtime/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
  itests/org.openhab.core.automation.integration.tests/itest.bndrun
  itests/org.openhab.core.automation.module.core.tests/itest.bndrun
  itests/org.openhab.core.automation.module.script.tests/itest.bndrun
  itests/org.openhab.core.automation.module.timer.tests/itest.bndrun
  itests/org.openhab.core.automation.tests/itest.bndrun
  itests/org.openhab.core.ephemeris.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
Labels: enhancement

#4375 Extend NetUtils for network range scanning
  bundles/org.openhab.core/src/main/java/org/openhab/core/net/NetUtil.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/net/NetUtilTest.java
Labels: enhancement

#4401 Add ColorUtil.xyToDuv
  bundles/org.openhab.core/src/main/java/org/openhab/core/util/ColorUtil.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/util/ColorUtilTest.java
Labels: enhancement

#4384 Extend HistoricItem to work with Instant instead of ZonedDateTime
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResource.java
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/HistoricItem.java
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceManagerImpl.java
  bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/defaultchartprovider/DefaultChartProvider.java
Labels: enhancement

#4415 Improve marketplace remote handling
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonService.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java
Labels: bug

#4392 Enhance ThingActions UI support
  bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/ThingActionsResource.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/AnnotationActionHandler.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/provider/AnnotatedActionModuleTypeProvider.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/module/provider/AnnotationActionModuleTypeHelper.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/thingsupport/AnnotatedThingActionModuleTypeProvider.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/util/ActionInputsHelper.java
  bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/provider/AnnotationActionModuleTypeProviderTest.java
  bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/thingsupport/AnnotatedThingActionModuleTypeProviderTest.java
  bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/util/ActionInputHelperTest.java
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigDescriptionParameter.java
Labels: enhancement

#4417 Parse BigInteger directly in DecimalType
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DecimalType.java
Labels: enhancement

#4416 Upgrade lastnpe EEA to 2.4.0
  bundles/org.openhab.core.io.transport.modbus/src/test/java/org/openhab/core/io/transport/modbus/test/SmokeTest.java
  bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/AbstractFileTransformationService.java
  pom.xml
Labels: dependencies

#4421 ActionOutput: Document QR code rendering & Fix action REST doc
  bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/ThingActionsResource.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/annotation/ActionOutput.java
Labels: bug, enhancement

#4428 ConfigDescriptionParameter: Change default format for datetime & Update context docs
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/util/ActionInputsHelper.java
  bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/util/ActionInputHelperTest.java
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigDescriptionParameter.java
Labels: enhancement

#4425 ConfigDescriptionParameter: Document how to allow any step size
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigDescriptionParameter.java
Labels: documentation

#4424 ActionInputsHelper: Allow any number of decimals & Apply primitive input default values
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/util/ActionInputsHelper.java
  bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/util/ActionInputHelperTest.java
Labels: enhancement

#4430 Thing actions: Support `@ActionOutput` for single return values
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/annotation/ActionOutput.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/AnnotationActionHandler.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/module/provider/AnnotationActionModuleTypeHelper.java
Labels: enhancement

#4429 [ColorUtil] Extend Colour Temperature range 1000 K .. 10000 K
  bundles/org.openhab.core/src/main/java/org/openhab/core/util/ColorUtil.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/util/ColorUtilTest.java
Labels: enhancement
