Repository openhab/openhab-core, pull requests merged in 2024-07, with the labels that each got.

#4284 Fix parsing of mac address in SDDP Discovery
  bundles/org.openhab.core.config.discovery.sddp/src/main/java/org/openhab/core/config/discovery/sddp/SddpDevice.java
  bundles/org.openhab.core.config.discovery.sddp/src/test/java/org/openhab/core/config/discovery/sddp/test/SddpDiscoveryServiceTests.java
Labels: bug, regression

#4288 Ensure the PoolBasedSequentialScheduledExecutorService does keep a minimum size
  bundles/org.openhab.core/src/main/java/org/openhab/core/common/PoolBasedSequentialScheduledExecutorService.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/common/ThreadPoolManager.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/common/ThreadPoolManagerTest.java
Labels: bug, regression

#4299 Fix AccessDeniedException in YamlModelRepository
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImpl.java
Labels: bug

#4298 [PersistenceExtensions] Fix TimeSeries policy `REPLACE` not being applied
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
Labels: bug

#4289 [rules] Add support for pre-compilation of conditions and actions
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/AbstractScriptModuleHandler.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/ScriptActionHandler.java
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/ScriptConditionHandler.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/handler/ActionHandler.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/handler/ConditionHandler.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
Labels: enhancement

#4313 Fix Timer.isRunning() returning true immediately after rescheduling
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/action/TimerImpl.java
  bundles/org.openhab.core.automation.module.script/src/test/java/org/openhab/core/automation/module/script/TimerImplTest.java
Labels: bug

#4312 Fix dynamic binding of AddonService to ConsoleCommandExtension service
  bundles/org.openhab.core.io.console/src/main/java/org/openhab/core/io/console/internal/extension/AddonConsoleCommandExtension.java
Labels: bug

#4311 Add a warning log to mention the field when configuration parsing is …
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigParser.java
Labels: enhancement

#4317 Add unitHint to AbstractStorageBasedTypeProvider.ChannelTypeEntity
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/AbstractStorageBasedTypeProvider.java
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/binding/AbstractStorageBasedTypeProviderTest.java
Labels: bug

#4314 Add default scope to profile when loading items file
  bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/GenericItemChannelLinkProvider.java
Labels: enhancement

#4319 [rules] Remove leftover from rfc in #4289
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/AbstractScriptModuleHandler.java
Labels: bug

#4320 Add missing system profile types and UIDs
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemProfileFactory.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/profiles/SystemProfiles.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/profiles/SystemProfileFactoryOSGiTest.java
Labels: bug

#4323 Fix startup of background discovery
  bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractThingHandlerDiscoveryService.java
Labels: bug

#4318 Add test to ensure full mapping of types in AbstractStorageBasedProvider
  bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/binding/AbstractStorageBasedTypeProviderTest.java
Labels: test

#4329 [rules] Don't attempt to pre-compile disabled rules
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
Labels: bug, regression
