Repository openhab/openhab-core, pull requests merged in 2024-03, with the labels that each got.

#4116 Audio parsing : Fix byte / bit confusion
  bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/utils/AudioSinkUtilsImpl.java
  bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/utils/AudioWaveUtils.java
Labels: bug

#4123 Add numericState and unit to StateDTO
  bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/SseItemStatesEventBuilder.java
  bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/dto/StateDTO.java
Labels: enhancement

#4110 Script profile: Fix deprecation warning for `toHandlerScript`
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/profile/ScriptProfile.java
  bundles/org.openhab.core.automation.module.script/src/test/java/org/openhab/core/automation/module/script/profile/ScriptProfileTest.java
Labels: regression

#4097 Call, Contact, Image items: Don't create command descr from state descr
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/GenericItem.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/CallItem.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/ContactItem.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/ImageItem.java
Labels: bug

#4136 [rest] stream json without starting a new thread
  bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/internal/config/ConfigDescriptionResourceTest.java
  bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/JSONResponse.java
  bundles/org.openhab.core.io.rest/src/test/java/org/openhab/core/io/rest/JSONResponseTest.java
  itests/org.openhab.core.io.rest.core.tests/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResourceOSGiTest.java
  itests/org.openhab.core.io.rest.core.tests/src/main/java/org/openhab/core/io/rest/core/internal/link/ItemChannelLinkResourceOSGiTest.java
Labels: enhancement

#4129 [auth] Set doctype for auth page
  bundles/org.openhab.core.io.http.auth/pages/authorize.html
Labels: bug

#4106 unitSymbol in REST response for GroupItem
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/item/EnrichedItemDTOMapper.java
Labels: enhancement

#4119 [rest] Enable filters for cacheable items list
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java
Labels: bug

#4099 [rest] refactored the Stream2JSONInputStream to simplify the logic
  bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/Stream2JSONInputStream.java
Labels: enhancement

#4145 [rest] special handling for StreamingOutput
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/GsonMessageBodyWriter.java
Labels: regression

#4108 [rest] Skip ignored things in inbox by default
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/discovery/InboxResource.java
Labels: enhancement

#4150 [oauth] Fix exception wrapping
  bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthConnector.java
Labels: bug

#4137 REST response default persistence strategy when no persistence configuration
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResource.java
Labels: enhancement

#4107 [rest] Add caching for add-on resource
  bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/RuleResource.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/addons/AddonResource.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/tag/TagResource.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java
  bundles/org.openhab.core.io.rest.ui/src/main/java/org/openhab/core/io/rest/ui/internal/UIResource.java
  bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/RESTConstants.java
  bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/resources/SystemInfoResource.java
Labels: enhancement, REST/SSE

#4160 [rest] TokenResource: Set SameSite attribute for session id cookie
  bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/TokenResource.java
Labels: bug, REST/SSE

#4162 [automation] Avoid memory leak on script loading failure
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java
Labels: bug
