Repository openhab/openhab-core, pull requests merged in 2024-05, with the labels that each got.

#3652 Improvement: Allow subscriptions for complete sitemaps (not limited to a single page)
  bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/SitemapSubscriptionService.java
  bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java
  bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/WidgetsChangeListener.java
  bundles/org.openhab.core.io.rest.sitemap/src/test/java/org/openhab/core/io/rest/sitemap/internal/SitemapResourceTest.java
Labels: enhancement

#4076 .things file: fix change detection
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigUtil.java
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/normalization/DecimalNormalizer.java
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/normalization/NormalizerFactory.java
  bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/ConfigurationTest.java
  bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/internal/normalization/NormalizerTest.java
  bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/GenericThingProvider.xtend
Labels: bug

#3736 Return units in persistence extension commands and support future persisted states
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
  bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java
  bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/TestCachedValuesPersistenceService.java
  bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/TestPersistenceService.java
Labels: enhancement, API breaking

#4175 Set a default presentation pattern for String/Number/Datetime items
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ChannelStateDescriptionProvider.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/DefaultStateDescriptionFragmentProvider.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ItemRegistryImpl.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/internal/service/StateDescriptionServiceImplTest.java
  itests/org.openhab.core.tests/src/main/java/org/openhab/core/items/ItemRegistryImplTest.java
Labels: enhancement

#4206 Fix initial suggestion finder installation
  bundles/org.openhab.core.config.discovery.addon/src/main/java/org/openhab/core/config/discovery/addon/AddonSuggestionService.java
Labels: bug, regression

#4212 Persistence extension, re-add deprecated evolutionRate method variants
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
Labels: bug, regression

#4209 Fix suggestion finder installation
  bundles/org.openhab.core.config.discovery.addon/src/main/java/org/openhab/core/config/discovery/addon/AddonSuggestionService.java
Labels: bug

#4198 Reuse existing BigDecimals in rules while converting types
  bundles/org.openhab.core.model.script/src.moved/test/java/org/openhab/core/model/script/lib/NumberExtensionsTest.java
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/lib/NumberExtensions.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DecimalType.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/PercentType.java
Labels: enhancement

#4214 Prevent potential incorrect cache lookup due to hash collisions
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/CommunicationManager.java
Labels: enhancement

#4204 Support press and release buttons in sitemap generator
  bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
Labels: enhancement, sitemap

#4219 Fix textual things not updating on the first change
  bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/GenericThingProvider.xtend
Labels: bug, regression

#4213 Persistence extensions: allow null serviceId
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
Labels: enhancement

#4224 Fix resolver errors during bundle add-on installation
  bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java
  features/karaf/openhab-core/src/main/feature/feature.xml
Labels: bug, critical

#4036 Add IP broadcast add-on finder for suggestions
  bundles/org.openhab.core.config.discovery.addon.ip/src/main/java/org/openhab/core/config/discovery/addon/ip/IpAddonFinder.java
Labels: enhancement

#4226 [sitemap] Do not try to convert item state into OnOffType for Switch widget if item has options
  bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java
Labels: bug

#4217 Improve thing description XSD
  bundles/org.openhab.core.thing/schema/thing/thing-description-1.0.0.xsd
Labels: enhancement

#4233 Align I18nProviderImpl and thing description XSD
  bundles/org.openhab.core.thing/schema/thing/thing-description-1.0.0.xsd
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java
Labels: bug, critical

#4229 Update i18n property files
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/resources/OH-INF/i18n/jsr223.properties
  bundles/org.openhab.core.test.magic/src/main/resources/OH-INF/i18n/magic.properties
  bundles/org.openhab.core.ui/src/main/resources/OH-INF/i18n/chart.properties
  bundles/org.openhab.core.voice/src/main/resources/OH-INF/i18n/voice.properties
Labels: translation

#4218 Enable spotless for schema XSD
  bundles/org.openhab.core.addon/schema/addon-1.0.0.xsd
  bundles/org.openhab.core.addon/schema/addon-info-list-1.0.0.xsd
  bundles/org.openhab.core.config.core/schema/config-description-1.0.0.xsd
  bundles/org.openhab.core.thing/schema/update/update-description-1.0.0.xsd
  pom.xml
Labels: infrastructure

#4235 Fix exception in WindowsUsbSerialDiscovery
  bundles/org.openhab.core.config.discovery.usbserial.windowsregistry/src/main/java/org/openhab/core/config/discovery/usbserial/windowsregistry/internal/WindowsUsbSerialDiscovery.java
Labels: bug

#4181 Upgrade Karaf from 4.4.5 to 4.4.6
  bom/compile-model/pom.xml
  bom/compile/pom.xml
  bom/runtime/pom.xml
  bom/test/pom.xml
  bundles/org.openhab.core.io.console.eclipse/pom.xml
  bundles/org.openhab.core.io.jetty.certificate/pom.xml
  bundles/org.openhab.core.io.transport.modbus/pom.xml
  bundles/org.openhab.core.model.item/pom.xml
  bundles/org.openhab.core.model.persistence/pom.xml
  bundles/org.openhab.core.model.rule/pom.xml
  bundles/org.openhab.core.model.script/pom.xml
  bundles/org.openhab.core.model.sitemap/pom.xml
  bundles/org.openhab.core.model.thing/pom.xml
  bundles/org.openhab.core.semantics/pom.xml
  bundles/pom.xml
  features/karaf/openhab-core/pom.xml
  features/karaf/openhab-core/src/main/feature/feature.xml
  features/karaf/openhab-tp/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
  itests/org.openhab.core.addon.tests/itest.bndrun
  itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun
  itests/org.openhab.core.automation.integration.tests/itest.bndrun
  itests/org.openhab.core.automation.module.core.tests/itest.bndrun
  itests/org.openhab.core.automation.module.script.tests/itest.bndrun
  itests/org.openhab.core.automation.module.timer.tests/itest.bndrun
  itests/org.openhab.core.automation.tests/itest.bndrun
  itests/org.openhab.core.config.core.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun
  itests/org.openhab.core.config.dispatch.tests/itest.bndrun
  itests/org.openhab.core.ephemeris.tests/itest.bndrun
  itests/org.openhab.core.io.net.tests/itest.bndrun
  itests/org.openhab.core.io.rest.core.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
  itests/org.openhab.core.storage.json.tests/itest.bndrun
  itests/org.openhab.core.tests/itest.bndrun
  itests/org.openhab.core.thing.tests/itest.bndrun
  itests/org.openhab.core.voice.tests/itest.bndrun
  pom.xml
  tools/upgradetool/pom.xml
Labels: enhancement, security

#4242 Fix brightness in generic ColorChannelHandler
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/generic/converter/ColorChannelHandler.java
Labels: bug

#4252 Add .xsd to .gitattributes
  .gitattributes
Labels: enhancement

#4216 Add support for marketplace transformations
  bundles/org.openhab.core.addon.marketplace.karaf/src/main/java/org/openhab/core/addon/marketplace/karaf/internal/community/CommunityKarafAddonHandler.java
  bundles/org.openhab.core.addon.marketplace/pom.xml
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/MarketplaceConstants.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityBlockLibaryAddonHandler.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityBundleAddonHandler.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityRuleTemplateAddonHandler.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityTransformationAddonHandler.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityUIWidgetAddonHandler.java
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java
Labels: enhancement

#4237 New SDDP service for addon discovery and thing discovery
  bom/openhab-core/pom.xml
  bundles/org.openhab.core.config.discovery.addon.sddp/.classpath
  bundles/org.openhab.core.config.discovery.addon.sddp/.project
  bundles/org.openhab.core.config.discovery.addon.sddp/NOTICE
  bundles/org.openhab.core.config.discovery.addon.sddp/pom.xml
  bundles/org.openhab.core.config.discovery.addon.sddp/src/main/java/org/openhab/core/config/discovery/addon/sddp/SddpAddonFinder.java
  bundles/org.openhab.core.config.discovery.addon.sddp/src/test/java/org/openhab/core/config/discovery/addon/sddp/test/SddpAddonFinderTests.java
  bundles/org.openhab.core.config.discovery.addon/src/main/java/org/openhab/core/config/discovery/addon/AddonFinderConstants.java
  bundles/org.openhab.core.config.discovery.sddp/.classpath
  bundles/org.openhab.core.config.discovery.sddp/.project
  bundles/org.openhab.core.config.discovery.sddp/NOTICE
  bundles/org.openhab.core.config.discovery.sddp/pom.xml
  bundles/org.openhab.core.config.discovery.sddp/src/main/java/org/openhab/core/config/discovery/sddp/SddpDevice.java
  bundles/org.openhab.core.config.discovery.sddp/src/main/java/org/openhab/core/config/discovery/sddp/SddpDeviceParticipant.java
  bundles/org.openhab.core.config.discovery.sddp/src/main/java/org/openhab/core/config/discovery/sddp/SddpDiscoveryParticipant.java
  bundles/org.openhab.core.config.discovery.sddp/src/main/java/org/openhab/core/config/discovery/sddp/SddpDiscoveryService.java
  bundles/org.openhab.core.config.discovery.sddp/src/test/java/org/openhab/core/config/discovery/sddp/test/SddpDiscoveryServiceTests.java
  bundles/org.openhab.core/src/main/resources/OH-INF/config/addons.xml
  bundles/org.openhab.core/src/main/resources/OH-INF/i18n/addons.properties
  bundles/pom.xml
  features/karaf/openhab-core/src/main/feature/feature.xml
Labels: enhancement
