Repository openhab/openhab-core, pull requests merged in 2024-04, with the labels that each got.

#4165 Move to JUPnP v3.0.1
  bom/compile/pom.xml
  bom/runtime/pom.xml
  bundles/org.openhab.core.config.jupnp/pom.xml
  bundles/org.openhab.core.config.jupnp/src/main/java/org/openhab/core/config/jupnp/internal/OHUpnpServiceConfiguration.java
  features/karaf/openhab-tp/src/main/feature/feature.xml
Labels: enhancement

#4164 [util] Add abbreviate method
  bundles/org.openhab.core/src/main/java/org/openhab/core/util/StringUtils.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/util/StringUtilsTest.java
Labels: enhancement

#4182 Fix marketplace showing incompatible add-ons by default
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonService.java
Labels: bug

#4178 Upgrade Jollyday to 0.27.0
  bom/compile/pom.xml
  bom/runtime/pom.xml
  bundles/org.openhab.core.ephemeris/src/main/java/org/openhab/core/ephemeris/internal/EphemerisManagerImpl.java
  features/karaf/openhab-tp/src/main/feature/feature.xml
  itests/org.openhab.core.automation.integration.tests/itest.bndrun
  itests/org.openhab.core.automation.module.core.tests/itest.bndrun
  itests/org.openhab.core.automation.module.script.tests/itest.bndrun
  itests/org.openhab.core.automation.module.timer.tests/itest.bndrun
  itests/org.openhab.core.automation.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun
  itests/org.openhab.core.ephemeris.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
Labels: enhancement, dependencies

#4190 Use flatMap to simplify map operations
  bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptFileWatcher.java
  bundles/org.openhab.core.config.discovery.usbserial.ser2net/src/main/java/org/openhab/core/config/discovery/usbserial/ser2net/internal/Ser2NetUsbSerialDiscovery.java
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImpl.java
Labels: enhancement

#4187 Reduce SAT warnings
  bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/PipedAudioStream.java
  bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/DiscoveryServiceRegistryImpl.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/addons/AddonResource.java
  bundles/org.openhab.core.model.yaml/src/test/java/org/openhab/core/model/yaml/test/FirstTypeDTO.java
  bundles/org.openhab.core.model.yaml/src/test/java/org/openhab/core/model/yaml/test/SecondTypeDTO.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/ItemChannelLinkRegistry.java
Labels: enhancement

#4194 [persistence] improve building the ItemHistoryDTO
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResource.java
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/dto/ItemHistoryDTO.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java
Labels: enhancement

#4191 More instanceof pattern matching
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleRegistryImpl.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/AnnotationActionHandler.java
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/normalization/BooleanNormalizer.java
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/normalization/DecimalNormalizer.java
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/normalization/IntNormalizer.java
  bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/internal/WebClientFactoryImpl.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java
  bundles/org.openhab.core.model.item/src/org/openhab/core/model/item/internal/GenericItemProvider.java
  bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/lib/NumberExtensions.java
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/filter/PersistenceThresholdFilter.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ChannelStateDescriptionProvider.java
  bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/GroupFunctionHelper.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/MetadataStateDescriptionFragmentProvider.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/net/HttpServiceUtil.java
Labels: enhancement

#4197 Update plugins
  bundles/org.openhab.core.audio/pom.xml
  bundles/org.openhab.core.io.jetty.certificate/pom.xml
  bundles/org.openhab.core.io.monitor/pom.xml
  bundles/org.openhab.core.io.transport.modbus/pom.xml
  bundles/pom.xml
  itests/pom.xml
  pom.xml
  tools/archetype/binding/pom.xml
  tools/i18n-plugin/pom.xml
  tools/upgradetool/pom.xml
Labels: infrastructure

#4188 Use FeatureInstaller for suggestion finder installation
  bundles/org.openhab.core.config.discovery.addon/src/main/java/org/openhab/core/config/discovery/addon/AddonFinderConstants.java
  bundles/org.openhab.core.config.discovery.addon/src/main/java/org/openhab/core/config/discovery/addon/AddonSuggestionService.java
  bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java
  bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonFinderService.java
Labels: bug

#4185 GsonBuilder: Explicitly set date format
  bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthConnector.java
  bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthStoreHandlerImpl.java
  bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/parser/gson/AbstractGSONParser.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/MediaTypeExtension.java
  bundles/org.openhab.core.io.rest/src/test/java/org/openhab/core/io/rest/Stream2JSONInputStreamTest.java
  bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/JsonStorage.java
  bundles/org.openhab.core.storage.json/src/test/java/org/openhab/core/storage/json/internal/JsonStorageTest.java
  bundles/org.openhab.core.storage.json/src/test/java/org/openhab/core/storage/json/internal/PersistedTransformationMigratorTest.java
  bundles/org.openhab.core.storage.json/src/test/java/org/openhab/core/storage/json/internal/ThingStorageEntityMigratorTest.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DateTimeType.java
Labels: enhancement

#3847 [modbus] reduce log level when modbus slave returns DEVICE_BUSY exception
  bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/ModbusManagerImpl.java
Labels: bug

#4199 Fix inital loading and improve code for YAML model
  bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImpl.java
  bundles/org.openhab.core.model.yaml/src/test/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImplTest.java
  bundles/org.openhab.core.model.yaml/src/test/resources/model/addToModelExpectedContent.yaml
  bundles/org.openhab.core.model.yaml/src/test/resources/model/modelFileAddedOrRemoved.yaml
  bundles/org.openhab.core.model.yaml/src/test/resources/model/modelFileUpdatePost.yaml
  bundles/org.openhab.core.model.yaml/src/test/resources/model/modelFileUpdatePre.yaml
  bundles/org.openhab.core.model.yaml/src/test/resources/model/modifyModelInitialContent.yaml
  bundles/org.openhab.core.model.yaml/src/test/resources/model/removeFromModelExpectedContent.yaml
  bundles/org.openhab.core.model.yaml/src/test/resources/model/updateInModelExpectedContent.yaml
Labels: bug
