Repository openhab/openhab-core, pull requests merged in 2025-07, with the labels that each got.

#4888 Log the link in the ScriptProfile execution error message
  bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/profile/ScriptProfile.java
Labels: enhancement

#4896 Fix NPE in FolderObserver
  bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/internal/folder/FolderObserver.java
Labels: bug

#4897 Fix ready marker not set for model when folder is missing
  bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/internal/folder/FolderObserver.java
Labels: bug

#4900 Registry: Avoid warn log when adding ActionType/Metadata several times
  bundles/org.openhab.core/src/main/java/org/openhab/core/common/registry/AbstractRegistry.java
Labels: bug, regression

#4905 Restrict CORS logging to a single time
  bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/filter/CorsFilter.java
Labels: bug

#4912 Fixed translations for system-channel-type electric:energy
  bundles/org.openhab.core.thing/src/main/resources/OH-INF/i18n/DefaultSystemChannels.properties
Labels: bug, i18n/l10n

#4917 Map chart interpolation parameter into sitemap JSON response
  bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java
  bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/WidgetDTO.java
Labels: bug

#4934 Use Maven wrapper with GHA
  .github/scripts/maven-build
  .github/workflows/ci-build.yml
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: infrastructure
