Repository openhab/openhab-core, pull requests merged in 2025-02, with the labels that each got.

#4574 Fix managed transformations retrieval
  bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityTransformationAddonHandler.java
Labels: bug

#4486 Some non null annotations
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemProfileFactory.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/i18n/ProfileI18nUtil.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/profiles/i18n/ProfileTypeI18nLocalizationService.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/Activator.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/OpenHAB.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/common/osgi/ResourceBundleClassLoader.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/common/WrappedScheduledExecutorService.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/LanguageResourceBundleManager.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/internal/service/BundleResolverImpl.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/util/BundleResolver.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/i18n/ThingStatusInfoI18nLocalizationServiceOSGiTest.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ChannelCommandDescriptionProviderOSGiTest.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ChannelStateDescriptionProviderOSGiTest.java
  itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/update/ThingUpdateOSGiTest.java
Labels: enhancement

#4351 Add `getLastStateChange`, `getLastStateUpdate`, and `getLastState` to GenericItem
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/item/EnrichedGroupItemDTO.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/item/EnrichedItemDTO.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/item/EnrichedItemDTOMapper.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/GenericItem.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/Item.java
  bundles/org.openhab.core/src/test/java/org/openhab/core/items/GenericItemTest.java
Labels: enhancement

#4463 Persistence restore lastState and lastStateChange on startup
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/PersistedItem.java
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/QueryablePersistenceService.java
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceManagerImpl.java
  bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/internal/PersistenceManagerTest.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/GenericItem.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/Item.java
Labels: enhancement

#4608 Revert ConfigUtil::normalizeType and fix null annotations
  bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigUtil.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/addons/AddonResource.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/service/ConfigurableServiceResource.java
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java
  itests/org.openhab.core.io.rest.core.tests/src/main/java/org/openhab/core/io/rest/core/internal/service/ConfigurableServiceResourceOSGiTest.java
Labels: regression

#4620 Upgrade Jollyday to 1.5.0
  bom/compile/pom.xml
  bom/runtime/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
  itests/org.openhab.core.automation.integration.tests/itest.bndrun
  itests/org.openhab.core.automation.module.core.tests/itest.bndrun
  itests/org.openhab.core.automation.module.script.tests/itest.bndrun
  itests/org.openhab.core.automation.module.timer.tests/itest.bndrun
  itests/org.openhab.core.automation.tests/itest.bndrun
  itests/org.openhab.core.ephemeris.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
Labels: enhancement
