Repository openhab/openhab-core, pull requests merged in 2025-06, with the labels that each got.

#4840 Use Maven 3.9.10 for CI build
  .github/workflows/ci-build.yml
Labels: infrastructure

#4843 Use gmavenplus-plugin
  bundles/org.openhab.core.semantics/pom.xml
Labels: infrastructure

#4862 Upgrade Jollyday to 1.5.4
  bom/compile/pom.xml
  bom/runtime/pom.xml
  features/karaf/openhab-tp/src/main/feature/feature.xml
  itests/org.openhab.core.automation.integration.tests/itest.bndrun
  itests/org.openhab.core.automation.module.core.tests/itest.bndrun
  itests/org.openhab.core.automation.module.script.tests/itest.bndrun
  itests/org.openhab.core.automation.module.timer.tests/itest.bndrun
  itests/org.openhab.core.automation.tests/itest.bndrun
  itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun
  itests/org.openhab.core.ephemeris.tests/itest.bndrun
  itests/org.openhab.core.model.item.tests/itest.bndrun
  itests/org.openhab.core.model.rule.tests/itest.bndrun
  itests/org.openhab.core.model.script.tests/itest.bndrun
  itests/org.openhab.core.model.thing.tests/itest.bndrun
Labels: enhancement, dependencies

#4871 Fix upgradetool dependencies, regression
  tools/upgradetool/pom.xml
Labels: bug, regression

#4827 Semantics health REST endpoint
  bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java
  bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/ItemSemanticsProblem.java
  bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/SemanticsService.java
  bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/internal/SemanticsServiceImpl.java
Labels: enhancement
