Repository openhab/openhab-core, pull requests merged in 2025-04, with the labels that each got.

#4640 Allow startlevel to increase past 80 when a bridge is disabled
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
Labels: bug

#4679 Fix timeseries restore init late initialization of listeners on GenericItem
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceManagerImpl.java
Labels: bug

#4728 Shorten logging of timeseries updates
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemTimeSeriesEvent.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemTimeSeriesUpdatedEvent.java
Labels: enhancement

#4751 Enable Dependabot PRs
  .github/dependabot.yml
Labels: infrastructure

#4764 Update Dependabot config
  .github/dependabot.yml
Labels: infrastructure, regression
