Repository openhab/openhab-core, pull requests merged in 2025-03, with the labels that each got.

#4637 Fix JavaDoc build
  bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/ModelRepository.java
  bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/fileconverter/AbstractThingFileGenerator.java
Labels: regression

#4647 Replace GH Action from tj-actions by custom code
  .github/workflows/ci-build.yml
Labels: infrastructure, security

#4632 OAuth RFC-8628 Device Code Grant Flow
  bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthClientServiceImpl.java
  bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthConnector.java
  bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthConnectorRFC8628.java
  bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthStoreHandler.java
  bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthStoreHandlerImpl.java
  bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/StorageRecordType.java
  bundles/org.openhab.core.auth.oauth2client/src/test/java/org/openhab/core/auth/oauth2client/internal/OAuthRFC8628ClientTest.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/auth/client/oauth2/DeviceCodeResponseDTO.java
  bundles/org.openhab.core/src/main/java/org/openhab/core/auth/client/oauth2/OAuthClientService.java
Labels: enhancement

#4461 Persistence Extensions: Riemann Sums
  bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
  bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java
  bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/TestPersistenceService.java
Labels: enhancement

#4660 Improve GitHub Action
  .github/workflows/ci-build.yml
Labels: infrastructure
